# Generated by Django 5.2.3 on 2026-01-11 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cluster', '0001_initial'),
        ('destination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text="Saisir l'adresse email", max_length=254, unique=True, verbose_name='Courriel')),
                ('first_name', models.CharField(help_text='Saisir le prénom', max_length=150, verbose_name='Prénom')),
                ('last_name', models.CharField(help_text='Saisir le nom de famille', max_length=150, verbose_name='Nom')),
                ('cellphone', models.CharField(blank=True, help_text='Saisir le numéro de téléphone portable', max_length=15, null=True, verbose_name='Téléphone portable')),
                ('lang_com', models.CharField(choices=[('en-us', 'Anglais (US)'), ('fr', 'Français'), ('de', 'Allemand'), ('es', 'Espagnol')], default='fr', help_text='Saisir la langue de communication', max_length=10, verbose_name='Langue de communication')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('code_cluster', models.ForeignKey(blank=True, help_text='Saisir le code du cluster', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cluster.cluster', verbose_name='Code du cluster')),
                ('code_dest', models.ForeignKey(blank=True, help_text='Saisir le code de la destination', null=True, on_delete=django.db.models.deletion.SET_NULL, to='destination.destination', verbose_name='Code de la destination')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
