# Generated by Django 5.2.3 on 2025-10-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_greeter_lang_com'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lang_com',
            field=models.CharField(choices=[('en-us', 'English (US)'), ('fr', 'Français'), ('de', 'Deutsch'), ('es', 'Español')], default='fr', max_length=10, verbose_name='Langue de communication'),
        ),
    ]
