# Generated by Django 5.2.3 on 2025-10-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_lang_com'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='lang_com',
            field=models.CharField(choices=[('en-us', 'Anglais (US)'), ('fr', 'Français'), ('de', 'Allemand'), ('es', 'Espagnol')], default='fr', max_length=10, verbose_name='Langue de communication'),
        ),
    ]
