# Generated by Django 5.2.3 on 2025-10-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_lang_com'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='code_cluster',
            field=models.CharField(default='', max_length=5, verbose_name='Code du cluster'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='code_destination',
            field=models.CharField(default='', max_length=5, verbose_name='Code de la destination'),
        ),
    ]
