# Generated by Django 5.2.3 on 2025-10-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_code_cluster_customuser_code_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='code_cluster',
            field=models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='Code du cluster'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='code_destination',
            field=models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='Code de la destination'),
        ),
    ]
