# Generated by Django 5.2.3 on 2025-11-09 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_code_cluster_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='code_destination',
            new_name='code_dest',
        ),
    ]
