# Generated by Django 5.2.3 on 2025-12-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_code_destination_customuser_code_dest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cellphone',
            field=models.CharField(blank=True, help_text='Saisir le numéro de téléphone portable', max_length=15, null=True, verbose_name='Téléphone portable'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lang_com',
            field=models.CharField(choices=[('en-us', 'Anglais (US)'), ('fr', 'Français'), ('de', 'Allemand'), ('es', 'Espagnol')], default='fr', help_text='Saisir la langue de communication', max_length=10, verbose_name='Langue de communication'),
        ),
        migrations.DeleteModel(
            name='Greeter',
        ),
    ]
