# Generated by Django 5.2.3 on 2026-01-11 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_beneficiaire', models.CharField(default='Pas de donation', max_length=100, verbose_name='Nom du bénéficiaire')),
                ('nom_beneficiaire_en_us', models.CharField(default='Pas de donation', max_length=100, null=True, verbose_name='Nom du bénéficiaire')),
                ('nom_beneficiaire_fr', models.CharField(default='Pas de donation', max_length=100, null=True, verbose_name='Nom du bénéficiaire')),
                ('nom_beneficiaire_de', models.CharField(default='Pas de donation', max_length=100, null=True, verbose_name='Nom du bénéficiaire')),
                ('nom_beneficiaire_es', models.CharField(default='Pas de donation', max_length=100, null=True, verbose_name='Nom du bénéficiaire')),
            ],
        ),
        migrations.CreateModel(
            name='Email_Mailjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_email', models.CharField(max_length=5, unique=True, verbose_name='Code_courriel')),
                ('name_email', models.CharField(max_length=100, verbose_name='Nom_courriel')),
                ('lang_email', models.CharField(choices=[('en-us', 'Anglais (US)'), ('fr', 'Français'), ('de', 'Allemand'), ('es', 'Espagnol')], default='fr', max_length=10, verbose_name='Langue')),
                ('id_mailjet_email', models.IntegerField(verbose_name='Id_template_mailjet')),
            ],
        ),
        migrations.CreateModel(
            name='Language_communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('name_en_us', models.CharField(max_length=50, null=True)),
                ('name_fr', models.CharField(max_length=50, null=True)),
                ('name_de', models.CharField(max_length=50, null=True)),
                ('name_es', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LangueDeepL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_iso', models.CharField(max_length=10, unique=True)),
                ('lang_deepl', models.CharField(default='Français', max_length=100, verbose_name='Langue')),
                ('lang_deepl_en_us', models.CharField(default='Français', max_length=100, null=True, verbose_name='Langue')),
                ('lang_deepl_fr', models.CharField(default='Français', max_length=100, null=True, verbose_name='Langue')),
                ('lang_deepl_de', models.CharField(default='Français', max_length=100, null=True, verbose_name='Langue')),
                ('lang_deepl_es', models.CharField(default='Français', max_length=100, null=True, verbose_name='Langue')),
            ],
        ),
        migrations.CreateModel(
            name='LangueParlee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_iso', models.CharField(max_length=2, unique=True)),
                ('langue_parlee', models.CharField(max_length=100, verbose_name='Langue parlée')),
                ('langue_parlee_en_us', models.CharField(max_length=100, null=True, verbose_name='Langue parlée')),
                ('langue_parlee_fr', models.CharField(max_length=100, null=True, verbose_name='Langue parlée')),
                ('langue_parlee_de', models.CharField(max_length=100, null=True, verbose_name='Langue parlée')),
                ('langue_parlee_es', models.CharField(max_length=100, null=True, verbose_name='Langue parlée')),
            ],
        ),
        migrations.CreateModel(
            name='No_show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_noshow', models.CharField(default='Pas de raison', max_length=100, verbose_name='Raison non réalisation')),
                ('raison_noshow_en_us', models.CharField(default='Pas de raison', max_length=100, null=True, verbose_name='Raison non réalisation')),
                ('raison_noshow_fr', models.CharField(default='Pas de raison', max_length=100, null=True, verbose_name='Raison non réalisation')),
                ('raison_noshow_de', models.CharField(default='Pas de raison', max_length=100, null=True, verbose_name='Raison non réalisation')),
                ('raison_noshow_es', models.CharField(default='Pas de raison', max_length=100, null=True, verbose_name='Raison non réalisation')),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_iso', models.CharField(max_length=3, unique=True)),
                ('nom_pays', models.CharField(max_length=100, verbose_name='Pays')),
                ('nom_pays_en_us', models.CharField(max_length=100, null=True, verbose_name='Pays')),
                ('nom_pays_fr', models.CharField(max_length=100, null=True, verbose_name='Pays')),
                ('nom_pays_de', models.CharField(max_length=100, null=True, verbose_name='Pays')),
                ('nom_pays_es', models.CharField(max_length=100, null=True, verbose_name='Pays')),
            ],
            options={
                'verbose_name_plural': 'Pays',
                'ordering': ['nom_pays'],
            },
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_journee', models.CharField(default='Dans la journée', max_length=100, verbose_name='Période de la journée')),
                ('periode_journee_en_us', models.CharField(default='Dans la journée', max_length=100, null=True, verbose_name='Période de la journée')),
                ('periode_journee_fr', models.CharField(default='Dans la journée', max_length=100, null=True, verbose_name='Période de la journée')),
                ('periode_journee_de', models.CharField(default='Dans la journée', max_length=100, null=True, verbose_name='Période de la journée')),
                ('periode_journee_es', models.CharField(default='Dans la journée', max_length=100, null=True, verbose_name='Période de la journée')),
            ],
        ),
        migrations.CreateModel(
            name='TrancheAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tranche_age', models.CharField(default='Adulte (30-65)', max_length=100, verbose_name="Tranche d'âge")),
                ('tranche_age_en_us', models.CharField(default='Adulte (30-65)', max_length=100, null=True, verbose_name="Tranche d'âge")),
                ('tranche_age_fr', models.CharField(default='Adulte (30-65)', max_length=100, null=True, verbose_name="Tranche d'âge")),
                ('tranche_age_de', models.CharField(default='Adulte (30-65)', max_length=100, null=True, verbose_name="Tranche d'âge")),
                ('tranche_age_es', models.CharField(default='Adulte (30-65)', max_length=100, null=True, verbose_name="Tranche d'âge")),
            ],
        ),
        migrations.CreateModel(
            name='Types_handicap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_handicap', models.CharField(default='Pas de handicap', max_length=50, verbose_name='Type de handicap')),
                ('type_handicap_en_us', models.CharField(default='Pas de handicap', max_length=50, null=True, verbose_name='Type de handicap')),
                ('type_handicap_fr', models.CharField(default='Pas de handicap', max_length=50, null=True, verbose_name='Type de handicap')),
                ('type_handicap_de', models.CharField(default='Pas de handicap', max_length=50, null=True, verbose_name='Type de handicap')),
                ('type_handicap_es', models.CharField(default='Pas de handicap', max_length=50, null=True, verbose_name='Type de handicap')),
            ],
        ),
        migrations.CreateModel(
            name='FieldPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('is_editable', models.BooleanField(default=True)),
                ('object_id', models.PositiveIntegerField()),
                ('app_name', models.CharField(max_length=50)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('group', models.ManyToManyField(related_name='fields_permissions', to='auth.group')),
                ('target_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_permissions', to='auth.group')),
            ],
            options={
                'verbose_name': 'Permission de champ',
                'verbose_name_plural': 'Permissions de champs',
                'unique_together': {('field_name', 'content_type', 'object_id', 'target_group', 'app_name')},
            },
        ),
    ]
