# Generated by Django 5.2.3 on 2025-09-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_beneficiaire', models.CharField(default='Pas de donation', max_length=100, verbose_name='Nom du bénéficiaire')),
            ],
        ),
        migrations.CreateModel(
            name='Email_Mailjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_email', models.CharField(max_length=5, unique=True, verbose_name='Code_courriel')),
                ('name_email', models.CharField(max_length=100, verbose_name='Nom_courriel')),
                ('lang_email', models.CharField(choices=[('en-us', 'English (US)'), ('fr', 'Français'), ('de', 'Deutsch'), ('es', 'Español')], default='fr', max_length=10, verbose_name='Langue')),
                ('id_mailjet_email', models.IntegerField(verbose_name='Id_template_mailjet')),
            ],
        ),
        migrations.CreateModel(
            name='InterestCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_center', models.CharField(max_length=100, verbose_name="Centre d'intérêt")),
                ('interest_center_en_us', models.CharField(max_length=100, null=True, verbose_name="Centre d'intérêt")),
                ('interest_center_fr', models.CharField(max_length=100, null=True, verbose_name="Centre d'intérêt")),
                ('interest_center_de', models.CharField(max_length=100, null=True, verbose_name="Centre d'intérêt")),
                ('interest_center_es', models.CharField(max_length=100, null=True, verbose_name="Centre d'intérêt")),
            ],
        ),
        migrations.CreateModel(
            name='LangueDeepL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_iso', models.CharField(max_length=10, unique=True)),
                ('lang_deepl', models.CharField(default='Français', max_length=100, verbose_name='Langue')),
                ('lang_deepl_en_us', models.CharField(default='Français', max_length=100, null=True, verbose_name='Langue')),
                ('lang_deepl_fr', models.CharField(default='Français', max_length=100, null=True, verbose_name='Langue')),
                ('lang_deepl_de', models.CharField(default='Français', max_length=100, null=True, verbose_name='Langue')),
                ('lang_deepl_es', models.CharField(default='Français', max_length=100, null=True, verbose_name='Langue')),
            ],
        ),
        migrations.CreateModel(
            name='LangueParlee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_iso', models.CharField(max_length=2, unique=True)),
                ('langue_parlee', models.CharField(max_length=100, verbose_name='Langue parlée')),
                ('langue_parlee_en_us', models.CharField(max_length=100, null=True, verbose_name='Langue parlée')),
                ('langue_parlee_fr', models.CharField(max_length=100, null=True, verbose_name='Langue parlée')),
                ('langue_parlee_de', models.CharField(max_length=100, null=True, verbose_name='Langue parlée')),
                ('langue_parlee_es', models.CharField(max_length=100, null=True, verbose_name='Langue parlée')),
            ],
        ),
        migrations.CreateModel(
            name='MaxVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_visitor', models.IntegerField(default=6, verbose_name='Nombre maximum de visiteurs')),
            ],
        ),
        migrations.CreateModel(
            name='No_show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_noshow', models.CharField(default='Pas de raison', max_length=100, verbose_name='Raison non réalisation')),
                ('raison_noshow_en_us', models.CharField(default='Pas de raison', max_length=100, null=True, verbose_name='Raison non réalisation')),
                ('raison_noshow_fr', models.CharField(default='Pas de raison', max_length=100, null=True, verbose_name='Raison non réalisation')),
                ('raison_noshow_de', models.CharField(default='Pas de raison', max_length=100, null=True, verbose_name='Raison non réalisation')),
                ('raison_noshow_es', models.CharField(default='Pas de raison', max_length=100, null=True, verbose_name='Raison non réalisation')),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_iso', models.CharField(max_length=3, unique=True)),
                ('nom_pays', models.CharField(max_length=100, verbose_name='Pays')),
                ('nom_pays_en_us', models.CharField(max_length=100, null=True, verbose_name='Pays')),
                ('nom_pays_fr', models.CharField(max_length=100, null=True, verbose_name='Pays')),
                ('nom_pays_de', models.CharField(max_length=100, null=True, verbose_name='Pays')),
                ('nom_pays_es', models.CharField(max_length=100, null=True, verbose_name='Pays')),
            ],
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_journee', models.CharField(default='Dans la journée', max_length=100, verbose_name='Période de la journée')),
                ('periode_journee_en_us', models.CharField(default='Dans la journée', max_length=100, null=True, verbose_name='Période de la journée')),
                ('periode_journee_fr', models.CharField(default='Dans la journée', max_length=100, null=True, verbose_name='Période de la journée')),
                ('periode_journee_de', models.CharField(default='Dans la journée', max_length=100, null=True, verbose_name='Période de la journée')),
                ('periode_journee_es', models.CharField(default='Dans la journée', max_length=100, null=True, verbose_name='Période de la journée')),
            ],
        ),
        migrations.CreateModel(
            name='TrancheAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tranche_age', models.CharField(default='Adulte (30-65)', max_length=100, verbose_name="Tranche d'âge")),
                ('tranche_age_en_us', models.CharField(default='Adulte (30-65)', max_length=100, null=True, verbose_name="Tranche d'âge")),
                ('tranche_age_fr', models.CharField(default='Adulte (30-65)', max_length=100, null=True, verbose_name="Tranche d'âge")),
                ('tranche_age_de', models.CharField(default='Adulte (30-65)', max_length=100, null=True, verbose_name="Tranche d'âge")),
                ('tranche_age_es', models.CharField(default='Adulte (30-65)', max_length=100, null=True, verbose_name="Tranche d'âge")),
            ],
        ),
        migrations.CreateModel(
            name='Types_handicap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_handicap', models.CharField(default='Pas de handicap', max_length=50, verbose_name='Type de handicap')),
                ('type_handicap_en_us', models.CharField(default='Pas de handicap', max_length=50, null=True, verbose_name='Type de handicap')),
                ('type_handicap_fr', models.CharField(default='Pas de handicap', max_length=50, null=True, verbose_name='Type de handicap')),
                ('type_handicap_de', models.CharField(default='Pas de handicap', max_length=50, null=True, verbose_name='Type de handicap')),
                ('type_handicap_es', models.CharField(default='Pas de handicap', max_length=50, null=True, verbose_name='Type de handicap')),
            ],
        ),
    ]
