# Generated by Django 5.2.3 on 2025-10-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_language_communication'),
    ]

    operations = [
        migrations.AddField(
            model_name='language_communication',
            name='name_de',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='language_communication',
            name='name_en_us',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='language_communication',
            name='name_es',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='language_communication',
            name='name_fr',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
