# Generated by Django 5.2.3 on 2025-10-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_language_communication_name_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_mailjet',
            name='lang_email',
            field=models.CharField(choices=[('en-us', 'Anglais (US)'), ('fr', 'Français'), ('de', 'Allemand'), ('es', 'Espagnol')], default='fr', max_length=10, verbose_name='Langue'),
        ),
    ]
