# Generated by Django 5.2.3 on 2025-10-19 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0005_clusterfieldpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('is_editable', models.BooleanField(default=True)),
                ('object_id', models.PositiveIntegerField()),
                ('app_name', models.CharField(max_length=50)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields_permissions', to='auth.group')),
                ('target_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_permissions', to='auth.group')),
            ],
            options={
                'verbose_name': 'Permission de champ',
                'verbose_name_plural': 'Permissions de champs',
                'unique_together': {('field_name', 'content_type', 'object_id', 'group', 'target_group', 'app_name')},
            },
        ),
    ]
