# Generated by Django 5.2.3 on 2025-10-27 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fieldpermission'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clusterfieldpermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='clusterfieldpermission',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='clusterfieldpermission',
            name='group',
        ),
        migrations.DeleteModel(
            name='MaxVisitor',
        ),
        migrations.DeleteModel(
            name='ClusterFieldPermission',
        ),
    ]
