# Generated by Django 5.2.3 on 2025-10-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0007_alter_clusterfieldpermission_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fieldpermission',
            unique_together={('field_name', 'content_type', 'object_id', 'target_group', 'app_name')},
        ),
        migrations.RemoveField(
            model_name='fieldpermission',
            name='group',
        ),
        migrations.AddField(
            model_name='fieldpermission',
            name='group',
            field=models.ManyToManyField(related_name='fields_permissions', to='auth.group'),
        ),
    ]
