# Generated by Django 5.2.3 on 2025-11-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_fieldpermission_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaire',
            name='nom_beneficiaire_de',
            field=models.CharField(default='Pas de donation', max_length=100, null=True, verbose_name='Nom du bénéficiaire'),
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='nom_beneficiaire_en_us',
            field=models.CharField(default='Pas de donation', max_length=100, null=True, verbose_name='Nom du bénéficiaire'),
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='nom_beneficiaire_es',
            field=models.CharField(default='Pas de donation', max_length=100, null=True, verbose_name='Nom du bénéficiaire'),
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='nom_beneficiaire_fr',
            field=models.CharField(default='Pas de donation', max_length=100, null=True, verbose_name='Nom du bénéficiaire'),
        ),
    ]
