# Generated by Django 5.2.3 on 2025-12-20 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_beneficiaire_nom_beneficiaire_de_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pays',
            options={'ordering': ['nom_pays'], 'verbose_name_plural': 'Pays'},
        ),
    ]
