# Generated by Django 5.2.3 on 2025-12-29 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_pays_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interestcenter',
            name='interest_center_de',
        ),
        migrations.RemoveField(
            model_name='interestcenter',
            name='interest_center_en_us',
        ),
        migrations.RemoveField(
            model_name='interestcenter',
            name='interest_center_es',
        ),
        migrations.RemoveField(
            model_name='interestcenter',
            name='interest_center_fr',
        ),
    ]
