# Generated by Django 5.2.3 on 2025-12-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_interestcenter_interest_center_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestcenter',
            name='interest_center_de',
            field=models.CharField(max_length=100, null=True, verbose_name="Centre d'intérêt"),
        ),
        migrations.AddField(
            model_name='interestcenter',
            name='interest_center_en_us',
            field=models.CharField(max_length=100, null=True, verbose_name="Centre d'intérêt"),
        ),
        migrations.AddField(
            model_name='interestcenter',
            name='interest_center_es',
            field=models.CharField(max_length=100, null=True, verbose_name="Centre d'intérêt"),
        ),
        migrations.AddField(
            model_name='interestcenter',
            name='interest_center_fr',
            field=models.CharField(max_length=100, null=True, verbose_name="Centre d'intérêt"),
        ),
    ]
