# Generated by Django 5.2.3 on 2025-12-29 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_interestcenter_interest_center_de_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InterestCenter',
        ),
    ]
