# Generated by Django 5.2.3 on 2026-01-04 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0013_delete_interestcenter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldpermission',
            name='group',
        ),
        migrations.AlterField(
            model_name='fieldpermission',
            name='app_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fieldpermission',
            name='field_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fieldpermission',
            name='target_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_field_permissions', to='auth.group'),
        ),
        migrations.AddIndex(
            model_name='fieldpermission',
            index=models.Index(fields=['content_type', 'object_id'], name='core_fieldp_content_198e9e_idx'),
        ),
    ]
