# Generated by Django 5.2.3 on 2026-01-04 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0014_remove_fieldpermission_group_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fieldpermission',
            name='core_fieldp_content_198e9e_idx',
        ),
        migrations.AddField(
            model_name='fieldpermission',
            name='group',
            field=models.ManyToManyField(related_name='fields_permissions', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='fieldpermission',
            name='app_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fieldpermission',
            name='field_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fieldpermission',
            name='target_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_permissions', to='auth.group'),
        ),
    ]
