# Generated by Django 5.2.3 on 2025-10-28 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cluster', '0011_alter_cluster_param_nbr_part_cluster'),
        ('core', '0007_alter_clusterfieldpermission_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_dest', models.CharField(default=' ', help_text='Saisir le code de la destination', max_length=5, unique=True, verbose_name='Code')),
                ('code_parent_dest', models.CharField(default=' ', help_text='Saisir le code parent de la destination', max_length=5, verbose_name='Code parent')),
                ('code_IGA_dest', models.CharField(default=' ', help_text='Saisir le code IGA de la destination', max_length=5, verbose_name='Code IGA')),
                ('name_dest', models.CharField(default=' ', help_text='Saisir le nom de la destination', max_length=30, verbose_name='Nom')),
                ('desc_dest', models.TextField(default=' ', help_text='Décrire la destination', max_length=100, verbose_name='Description')),
                ('adress_dest', models.CharField(default=' ', help_text="Saisir l'adresse de la destination", max_length=250, verbose_name='Adresse')),
                ('region_dest', models.CharField(default=' ', help_text='Saisir la région de la destination', max_length=50, verbose_name='Région')),
                ('logo_dest', models.ImageField(default='logos/default.jpg', help_text='Taille : 250 px *250 px', upload_to='logos/', verbose_name='Logo')),
                ('libelle_email_dest', models.CharField(default=' ', help_text='Saisir le libellé des courriels émetteurs de la destination', max_length=50, verbose_name='Libellé courriel émetteur ')),
                ('status_dest', models.CharField(choices=[('Drafts', 'Brouillon'), ('Active', 'Actif'), ('Inactive', 'Inactif'), ('Désactivated', 'Désactivé')], default='Drafts', help_text='Saisir le statut dela destination', max_length=15, verbose_name='Statut')),
                ('manager_name_dest', models.CharField(default=' ', help_text='Saisir le nom du manager de la destination', max_length=35, verbose_name='Nom du manager')),
                ('manager_email_dest', models.EmailField(default=' ', help_text="Saisir l'email du manager de la destination", max_length=254, verbose_name='Email du manager')),
                ('manager_tel_dest', models.CharField(default=' ', help_text='Saisir le téléphone du manager de la destination', max_length=20, verbose_name='Téléphone')),
                ('referent_name_dest', models.CharField(default=' ', help_text='Saisir le nom du référent de la destination', max_length=35, verbose_name='Nom du référent')),
                ('referent_email_dest', models.EmailField(default=' ', help_text="Saisir l'email du référent de la destination", max_length=254, verbose_name='Email du référent')),
                ('referent_tel_dest', models.CharField(default=' ', help_text='Saisir le téléphone du référent de la destination', max_length=20, verbose_name='Téléphone')),
                ('matcher_name_dest', models.CharField(default=' ', help_text='Saisir le nom du gestionnaire de la destination', max_length=35, verbose_name='Nom du gestionnairer')),
                ('matcher_email_dest', models.EmailField(default=' ', help_text="Saisir l'email du gestionnaire de la destination", max_length=254, verbose_name='Email du gestionnaire')),
                ('matcher_tel_dest', models.CharField(default=' ', help_text='Saisir le téléphone du gestionnaire de la destination', max_length=20, verbose_name='Téléphone')),
                ('matcher_alt_name_dest', models.CharField(default=' ', help_text='Saisir le nom du gestionnaire alternatif de la destination', max_length=35, verbose_name='Nom du gestionnaire alternatif')),
                ('matcher_alt_email_dest', models.EmailField(default=' ', help_text="Saisir l'email du gestionnaire alternatif de la destination", max_length=254, verbose_name='Email du gestionnaire alternatif')),
                ('matcher_alt_tel_dest', models.CharField(default=' ', help_text='Saisir le téléphone du gestionnaire alternatif de la destination', max_length=20, verbose_name='Téléphone')),
                ('finance_name_dest', models.CharField(default=' ', help_text='Saisir le nom du gestionnaire financier de la destination', max_length=35, verbose_name='Nom du gestionnaire financier')),
                ('finance_email_dest', models.EmailField(default=' ', help_text="Saisir l'email du gestionnaire financier de la destination", max_length=254, verbose_name='Email du gestionnaire financier')),
                ('finance_tel_dest', models.CharField(default=' ', help_text='Saisir le téléphone du gestionnaire financier de la destination', max_length=20, verbose_name='Téléphone')),
                ('list_places_dest', models.CharField(default=' ', help_text='Saisir les lieux ou thèmes de la destination', max_length=500, verbose_name='Liste des lieux ou thèmes')),
                ('max_lp_dest', models.IntegerField(default=1, help_text='Saisir le nombre maximum de lieux ou thèmes par le visiteur', verbose_name='Nombre maximum de lieux ou thèmes')),
                ('mini_lp_dest', models.IntegerField(default=1, help_text='Saisir le nombre minimum de lieux ou thèmes par le visiteur', verbose_name='Nombre minimum de lieux ou thèmes')),
                ('max_interest_center_dest', models.IntegerField(default=1, help_text="Saisir le nombre maximum de centres d'intérêts par le visiteur", verbose_name="Nombre maximum de centres d'intérêts")),
                ('mini_interest_center_dest', models.IntegerField(default=1, help_text="Saisir le nombre minimum de centres d'intérêts par le visiteur", verbose_name="Nombre minimum de centres d'intérêts")),
                ('URL_retry_dest', models.URLField(blank=True, default=None, help_text="Saisir l'URL de retour après la validation d'une demande", verbose_name='URL de retour')),
                ('Flag_stay_dest', models.BooleanField(default=False, help_text='Saisir les dates du séjour (Oui/non)?', verbose_name='Dates du séjour')),
                ('dispersion_param_dest', models.IntegerField(default=2, help_text='Saisir le paramètre de dispersion des dates demandées', verbose_name='Dispersion des dates demandées')),
                ('mail_notification_dest', models.EmailField(default=' ', help_text="Saisir l'email de notification", max_length=254, verbose_name='Email de notification')),
                ('mail_response_dest', models.EmailField(default=' ', help_text="Saisir l'email de réponse pour un courriel envoyé par le système", max_length=254, verbose_name='Email de réponse')),
                ('disability_dest', models.BooleanField(default=False, help_text='saisir si des handicap sont acceptés', verbose_name='Handicap accepté')),
                ('disability_libelle_dest', models.TextField(default=' ', help_text='Saisir la présentation de la gestion du handicap', max_length=500, verbose_name='Présentation de la gestion du handicap')),
                ('cluster_code_dest', models.ForeignKey(help_text='Sélectionner le cluster de la destination', limit_choices_to={'statut_cluster': 'Active'}, on_delete=django.db.models.deletion.PROTECT, related_name='destinations', to='cluster.cluster', verbose_name='Cluster')),
                ('country_dest', models.ForeignKey(help_text='Sélectionner le pays de la destination', on_delete=django.db.models.deletion.PROTECT, to='core.pays', verbose_name='Pays')),
            ],
        ),
    ]
