# Generated by Django 5.2.3 on 2025-10-29 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='finance_email_dest',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='finance_tel_dest',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='manager_email_dest',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='manager_tel_dest',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='matcher_alt_email_dest',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='matcher_alt_tel_dest',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='matcher_email_dest',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='matcher_tel_dest',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='referent_email_dest',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='referent_tel_dest',
        ),
        migrations.AddField(
            model_name='destination',
            name='list_places_dest_de',
            field=models.CharField(default=' ', help_text='Saisir les lieux ou thèmes de la destination', max_length=500, null=True, verbose_name='Liste des lieux ou thèmes'),
        ),
        migrations.AddField(
            model_name='destination',
            name='list_places_dest_en_us',
            field=models.CharField(default=' ', help_text='Saisir les lieux ou thèmes de la destination', max_length=500, null=True, verbose_name='Liste des lieux ou thèmes'),
        ),
        migrations.AddField(
            model_name='destination',
            name='list_places_dest_es',
            field=models.CharField(default=' ', help_text='Saisir les lieux ou thèmes de la destination', max_length=500, null=True, verbose_name='Liste des lieux ou thèmes'),
        ),
        migrations.AddField(
            model_name='destination',
            name='list_places_dest_fr',
            field=models.CharField(default=' ', help_text='Saisir les lieux ou thèmes de la destination', max_length=500, null=True, verbose_name='Liste des lieux ou thèmes'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='code_dest',
            field=models.CharField(default='', editable=False, help_text='Saisir le code de la destination', max_length=5, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='finance_name_dest',
            field=models.ForeignKey(blank=True, help_text='Saisir le nom du gestionnaire financier de la destination', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_name_dest', to=settings.AUTH_USER_MODEL, verbose_name='Nom du gestionnaire financier'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='manager_name_dest',
            field=models.ForeignKey(blank=True, help_text='Saisir le nom du manager de la destination', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_name_dest', to=settings.AUTH_USER_MODEL, verbose_name='Nom du manager'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='matcher_alt_name_dest',
            field=models.ForeignKey(blank=True, help_text='Saisir le nom du gestionnaire alternatif de la destination', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matcher_alt_name_dest', to=settings.AUTH_USER_MODEL, verbose_name='Nom du gestionnaire alternatif'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='matcher_name_dest',
            field=models.ForeignKey(blank=True, help_text='Saisir le nom du gestionnaire de la destination', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matcher_name_dest', to=settings.AUTH_USER_MODEL, verbose_name='Nom du gestionnairer'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='referent_name_dest',
            field=models.ForeignKey(blank=True, help_text='Saisir le nom du référent de la destination', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referent_name_dest', to=settings.AUTH_USER_MODEL, verbose_name='Nom du référent'),
        ),
    ]
