# Generated by Django 5.2.3 on 2026-01-11 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('destination', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='finance_dest',
            field=models.ForeignKey(help_text='Saisir le nom du gestionnaire financier de la destination', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_name_dest', to=settings.AUTH_USER_MODEL, verbose_name='Nom du gestionnaire financier'),
        ),
        migrations.AddField(
            model_name='destination',
            name='manager_dest',
            field=models.ForeignKey(help_text='Saisir le nom du manager de la destination', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_name_dest', to=settings.AUTH_USER_MODEL, verbose_name='Nom du manager'),
        ),
        migrations.AddField(
            model_name='destination',
            name='matcher_alt_dest',
            field=models.ForeignKey(blank=True, help_text='Saisir le nom du gestionnaire alternatif de la destination', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matcher_alt_name_dest', to=settings.AUTH_USER_MODEL, verbose_name='Nom du gestionnaire alternatif'),
        ),
        migrations.AddField(
            model_name='destination',
            name='matcher_dest',
            field=models.ForeignKey(help_text='Saisir le nom du gestionnaire de la destination', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matcher_name_dest', to=settings.AUTH_USER_MODEL, verbose_name='Nom du gestionnaire'),
        ),
        migrations.AddField(
            model_name='destination',
            name='referent_dest',
            field=models.ForeignKey(help_text='Saisir le nom du référent de la destination', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referent_name_dest', to=settings.AUTH_USER_MODEL, verbose_name='Nom du référent'),
        ),
        migrations.AddField(
            model_name='destination_data',
            name='beneficiaire_don_dest',
            field=models.ForeignKey(help_text='Sélectionner le bénéficiaire des dons pour la destination', on_delete=django.db.models.deletion.PROTECT, related_name='beneficiaire_des_dons', to='core.beneficiaire', verbose_name='Bénéficiaire des dons'),
        ),
        migrations.AddField(
            model_name='destination_data',
            name='code_dest_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='destination_data', to='destination.destination'),
        ),
        migrations.AddField(
            model_name='destination_data',
            name='lang_default_dest',
            field=models.ForeignKey(help_text='Sélectionner la langue de communication par défaut de la destination', on_delete=django.db.models.deletion.PROTECT, related_name='langue_defaut_dest', to='core.language_communication', verbose_name='Langue de communication par défaut'),
        ),
        migrations.AddField(
            model_name='destination_data',
            name='langs_com_dest',
            field=models.ManyToManyField(blank=True, help_text='Sélectionner les langues de communication de la destination', to='core.language_communication', verbose_name='Langues de communication'),
        ),
        migrations.AddField(
            model_name='destination_data',
            name='langs_parlee_dest',
            field=models.ManyToManyField(blank=True, help_text='Sélectionner les langues parlées dans la destination', to='core.langueparlee', verbose_name='Langues parlées'),
        ),
        migrations.AddField(
            model_name='destination_flux',
            name='code_dest_flux',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='destination_flux', to='destination.destination'),
        ),
        migrations.AddField(
            model_name='destination',
            name='list_places_dest',
            field=models.ManyToManyField(blank=True, help_text='Sélectionner les lieux ou thèmes de la destination', related_name='destinations', to='destination.list_places', verbose_name='Lieux ou thèmes'),
        ),
    ]
