# Generated by Django 5.2.3 on 2025-10-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0002_remove_destination_finance_email_dest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='code_dest',
            field=models.CharField(default='', help_text='Saisir le code de la destination', max_length=5, unique=True, verbose_name='Code'),
        ),
    ]
