# Generated by Django 5.2.3 on 2026-02-04 11:32

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0003_alter_destination_data_flag_noanswer_visitor_dest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='logo_dest',
            field=models.ImageField(blank=True, default='logos/default.jpg', help_text='Taille : 250 px *250 px', null=True, upload_to=core.utils.get_file_path, verbose_name='Logo'),
        ),
    ]
