# Generated by Django 5.2.3 on 2026-02-11 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('destination', '0004_alter_destination_logo_dest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='country_dest',
            field=models.ForeignKey(help_text='Sélectionner le pays de la destination', on_delete=django.db.models.deletion.PROTECT, related_name='country_dest', to='core.pays', verbose_name='Pays'),
        ),
    ]
