# Generated by Django 5.2.3 on 2025-11-04 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0004_destination_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination_flux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequence_mail_precoce', models.IntegerField(default=0, help_text='Saisir la fréquence des mails précoces en jours', verbose_name='Fréquence des mails précoces (en jours)')),
                ('confirmation_date_precoce_dest', models.IntegerField(default=0, help_text="Saisir le nombre de jours avant le passage en mode Traitement pour l'envoi du courriel de demande de  confirmation par le visiteur", verbose_name="Nombre de jours avant le passage en mode Traitement pour l'envoi du courriel de demande de  confirmation par le visiteur")),
                ('flux_treatement_dest', models.IntegerField(default=0, help_text='Saisir le nombre de jours avant le passage en mode Traitement', verbose_name='Nombre de jours avant le passage en mode Traitement')),
                ('flux_urgency_dest', models.IntegerField(default=0, help_text='Saisir le nombre de jours avant le passage en mode Urgent', verbose_name='Nombre de jours avant le passage en mode Urgent')),
                ('flux_delai_organsiation_dest', models.IntegerField(default=0, help_text='Saisir le nombre de jours minimum avant la date de la balade', verbose_name='Nombre de jours minimum avant la date de la balade')),
                ('flux_delai_max_greeter_dest', models.IntegerField(default=0, help_text='Saisir le nombre de jours maximum pour le Greeter pour répondre à une attribution', verbose_name='Nombre de jours maximum pour le Greeter')),
                ('flux_frequence_relance_greeter_dest', models.IntegerField(default=0, help_text="Saisir la fréquence pour l'envoi d'une relance au Greeter pour répondre à une attribution", verbose_name='Fréquence de relance du Greeter')),
                ('flux_delai_visiteur_max_dest', models.IntegerField(default=0, help_text='Saisir le nombre de jours maximum pour le visiteur pour répondre à une proposition', verbose_name='Nombre de jours maximum pour le visiteur')),
                ('flux_frequence_relance_visiteur_dest', models.IntegerField(default=0, help_text="Saisir la fréquence pour l'envoi d'une relance au visiteur pour répondre à une proposition", verbose_name='Fréquence de relance du visiteur')),
                ('flux_delai_pre_balade_dest', models.IntegerField(default=0, help_text="Saisir le nombre de jours avant la balade pour l'envoi du courriel de rappel au Greeter et au visiteur", verbose_name="Nombre de jours avant la balade pour l'envoi du courriel de rappel au Greeter et au visiteur")),
                ('flux_saisie_suivie_dest', models.IntegerField(default=0, help_text="Saisir le nombre de jours après la balade pour la saisie manuelle d'une balade", verbose_name="Nombre de jours après la balade pour la saisie manuelle d'une balade")),
                ('flux_delai_compte_rendu_dest', models.IntegerField(default=0, help_text="Saisir le nombre de jours après la balade pour l'envoi du courriel de demande de compte-rendu au Greeter", verbose_name="Nombre de jours pour l'envoi de la demande de compte-rendu au Greeter")),
                ('flux_frequence_compte_rendu_dest', models.IntegerField(default=0, help_text="Saisir la fréquence pour l'envoi d'une relance au Greeter pour le compte-rendu", verbose_name='Fréquence de relance pour le compte-rendu du Greeter')),
                ('flux_delai_envoi_avis_dest', models.IntegerField(default=0, help_text="Saisir le nombre de jours après la balade pour l'envoi du courriel d'avis au visiteur", verbose_name="Nombre de jours après la balade pour l'envoi du courriel d'avis au visiteur")),
                ('flux_frequence_envoi_avis_dest', models.IntegerField(default=0, help_text="Saisir la fréquence pour l'envoi d'une relance au visiteur pour l'avis", verbose_name="Fréquence de relance pour l'avis du visiteur")),
                ('flux_delai_avis_max_dest', models.IntegerField(default=0, help_text='Saisir le nombre de jours maximum pour le visiteur pour donner son avis', verbose_name='Nombre de jours maximum pour le visiteur pour donner son avis')),
                ('flux_rgpd_dest', models.IntegerField(default=0, help_text="Saisir le nombre de jours avant l'anomysation des données du visiteur", verbose_name="Nombre de jours avant l'anomysation des données")),
                ('code_dest', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='destination_flux', to='destination.destination')),
            ],
        ),
    ]
