# Generated by Django 5.2.3 on 2025-11-04 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0005_destination_flux'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination_data',
            old_name='code_dest',
            new_name='code_dest_data',
        ),
        migrations.RenameField(
            model_name='destination_flux',
            old_name='code_dest',
            new_name='code_dest_flux',
        ),
    ]
