# Generated by Django 5.2.3 on 2025-11-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0006_rename_code_dest_destination_data_code_dest_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination_data',
            name='Flag_modalités_dest',
            field=models.CharField(choices=[('C&G contrôlé', 'C&G contrôlé'), ('Greet & Greet direct', 'C&G direct'), ('Gest', 'Gestionnaire')], default='C&G', help_text='Saisir le type de gestion de la destination', max_length=20, verbose_name='Type de gestion'),
        ),
    ]
