# Generated by Django 5.2.3 on 2025-11-07 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0014_alter_cluster_country_admin_alt_cluster_and_more'),
        ('destination', '0007_alter_destination_data_flag_modalités_dest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='status_dest',
            new_name='statut_dest',
        ),
        migrations.AlterField(
            model_name='destination',
            name='cluster_code_dest',
            field=models.ForeignKey(help_text='Sélectionner le cluster de la destination', limit_choices_to={'statut_cluster': 'Active'}, on_delete=django.db.models.deletion.PROTECT, related_name='cluster_destinations', to='cluster.cluster', verbose_name='Cluster'),
        ),
    ]
