# Generated by Django 5.2.3 on 2025-11-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0008_rename_status_dest_destination_statut_dest_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='finance_name_dest',
            new_name='finance_dest',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='Flag_stay_dest',
            new_name='flag_stay_dest',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='manager_name_dest',
            new_name='manager_dest',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='matcher_alt_name_dest',
            new_name='matcher_alt_dest',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='matcher_name_dest',
            new_name='matcher_dest',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='referent_name_dest',
            new_name='referent_dest',
        ),
        migrations.AlterField(
            model_name='destination',
            name='code_IGA_dest',
            field=models.CharField(blank=True, default=' ', help_text='Saisir le code IGA de la destination', max_length=5, null=True, verbose_name='Code IGA'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='code_parent_dest',
            field=models.CharField(blank=True, default=' ', help_text='Saisir le code parent de la destination', max_length=5, null=True, verbose_name='Code parent'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='region_dest',
            field=models.CharField(blank=True, default=' ', help_text='Saisir la région de la destination', max_length=50, null=True, verbose_name='Région'),
        ),
    ]
