# Generated by Django 5.2.3 on 2025-11-09 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_beneficiaire_nom_beneficiaire_de_and_more'),
        ('destination', '0009_rename_finance_name_dest_destination_finance_dest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='destination_data',
            name='langs_parlee_dest',
            field=models.ManyToManyField(blank=True, help_text='Sélectionner les langues parlées dans la destination', to='core.langueparlee', verbose_name='Langues parlées'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='disability_libelle_dest',
            field=models.TextField(blank=True, default=' ', help_text='Saisir la présentation de la gestion du handicap', max_length=500, null=True, verbose_name='Présentation de la gestion du handicap'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='dispersion_param_dest',
            field=models.IntegerField(blank=True, default=2, help_text='Saisir le paramètre de dispersion des dates demandées', null=True, verbose_name='Dispersion des dates demandées'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='matcher_dest',
            field=models.ForeignKey(blank=True, help_text='Saisir le nom du gestionnaire de la destination', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matcher_name_dest', to=settings.AUTH_USER_MODEL, verbose_name='Nom du gestionnaire'),
        ),
    ]
