# Generated by Django 5.2.3 on 2025-11-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0010_destination_data_langs_parlee_dest_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='cluster_code_dest',
            new_name='code_cluster',
        ),
        migrations.AlterField(
            model_name='destination',
            name='disability_dest',
            field=models.BooleanField(default=False, help_text='Saisir si des visteurs ayant un handicap sont acceptés', verbose_name='Handicap accepté'),
        ),
    ]
