# Generated by Django 5.2.3 on 2025-11-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0011_rename_cluster_code_dest_destination_code_cluster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='disability_libelle_dest_de',
            field=models.TextField(blank=True, default=' ', help_text='Saisir la présentation de la gestion du handicap', max_length=500, null=True, verbose_name='Présentation de la gestion du handicap'),
        ),
        migrations.AddField(
            model_name='destination',
            name='disability_libelle_dest_en_us',
            field=models.TextField(blank=True, default=' ', help_text='Saisir la présentation de la gestion du handicap', max_length=500, null=True, verbose_name='Présentation de la gestion du handicap'),
        ),
        migrations.AddField(
            model_name='destination',
            name='disability_libelle_dest_es',
            field=models.TextField(blank=True, default=' ', help_text='Saisir la présentation de la gestion du handicap', max_length=500, null=True, verbose_name='Présentation de la gestion du handicap'),
        ),
        migrations.AddField(
            model_name='destination',
            name='disability_libelle_dest_fr',
            field=models.TextField(blank=True, default=' ', help_text='Saisir la présentation de la gestion du handicap', max_length=500, null=True, verbose_name='Présentation de la gestion du handicap'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='disability_dest',
            field=models.BooleanField(default=False, help_text='Cocher la case si des visteurs ayant un handicap sont acceptés', verbose_name='Handicap accepté'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='dispersion_param_dest',
            field=models.IntegerField(blank=True, default=0, help_text='Saisir le paramètre de dispersion des dates demandées', null=True, verbose_name='Dispersion des dates demandées'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='flag_stay_dest',
            field=models.BooleanField(default=False, help_text='Cocher la case si les dates du séjour sont obligatoires', verbose_name='Dates du séjour'),
        ),
    ]
