# Generated by Django 5.2.3 on 2025-11-11 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0012_destination_disability_libelle_dest_de_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination_data',
            old_name='date_debut_avis_mail_test_dest',
            new_name='date_debut_avis_mail_dest',
        ),
        migrations.RenameField(
            model_name='destination_data',
            old_name='date_fin_avis_mail_test_dest',
            new_name='date_fin_avis_mail_dest',
        ),
        migrations.RenameField(
            model_name='destination_data',
            old_name='texte_avis_mail_test_dest',
            new_name='texte_avis_mail_dest',
        ),
        migrations.RenameField(
            model_name='destination_data',
            old_name='texte_avis_mail_test_dest_de',
            new_name='texte_avis_mail_dest_de',
        ),
        migrations.RenameField(
            model_name='destination_data',
            old_name='texte_avis_mail_test_dest_en_us',
            new_name='texte_avis_mail_dest_en_us',
        ),
        migrations.RenameField(
            model_name='destination_data',
            old_name='texte_avis_mail_test_dest_es',
            new_name='texte_avis_mail_dest_es',
        ),
        migrations.RenameField(
            model_name='destination_data',
            old_name='texte_avis_mail_test_dest_fr',
            new_name='texte_avis_mail_dest_fr',
        ),
        migrations.RenameField(
            model_name='destination_data',
            old_name='titre_avis_mail_test_dest',
            new_name='titre_avis_mail_dest',
        ),
    ]
