# Generated by Django 5.2.3 on 2025-11-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0013_rename_date_debut_avis_mail_test_dest_destination_data_date_debut_avis_mail_dest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='logo_dest',
            field=models.ImageField(blank=True, default='logos/default.jpg', help_text='Taille : 250 px *250 px', null=True, upload_to='logos/', verbose_name='Logo'),
        ),
    ]
