# Generated by Django 5.2.3 on 2025-11-26 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0014_alter_destination_logo_dest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination_flux',
            old_name='flux_delai_organsiation_dest',
            new_name='flux_delai_organisation_dest',
        ),
    ]
