# Generated by Django 5.2.3 on 2025-11-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0015_rename_flux_delai_organsiation_dest_destination_flux_flux_delai_organisation_dest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination_data',
            name='donation_proposal_dest',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Saisir la proposition de don pour la destination', max_digits=10, verbose_name='Proposition de don'),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='flag_reason_NoAnswer_greeter_dest',
            field=models.BooleanField(default=False, help_text='Cocher si le motif de la non proposition du Greeter est obligatoire', verbose_name='Demander le motif la non-réponse du Greeter'),
        ),
    ]
