# Generated by Django 5.2.3 on 2025-11-30 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0016_alter_destination_data_donation_proposal_dest_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination_data',
            old_name='Flag_modalités_dest',
            new_name='flag_modalités_dest',
        ),
    ]
