# Generated by Django 5.2.3 on 2025-11-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0017_rename_flag_modalités_dest_destination_data_flag_modalités_dest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination_data',
            name='flag_NoAnswer_visitor_dest',
            field=models.CharField(choices=[('demande', 'Annulation demande'), ('proposition', 'Annulation proposition')], default='demande', help_text="Cocher l'action à effectuer suite à la non-réponse du visiteur", max_length=11, verbose_name='Action suite à la non-réponse du visiteur'),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='lib_url_form_coche1_dest',
            field=models.CharField(default=' ', help_text="Saisir le texte de l'URL liée à la première case à cocher sur le formulaire d'inscription", max_length=200, verbose_name="texte de l'URL de la première case à cocher"),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='lib_url_form_coche2_dest',
            field=models.CharField(default=' ', help_text="Saisir le texte de l'URL liée à la deuxième case à cocher sur le formulaire d'inscription", max_length=200, verbose_name="texte de l'URL de la deuxième case à cocher"),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='lib_url_form_coche3_dest',
            field=models.CharField(default=' ', help_text="Saisir le texte de l'URL liée à la troisième case à cocher sur le formulaire d'inscription", max_length=200, verbose_name="texte de l'URL de la troisième case à cocher"),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='url_form_coche1_dest',
            field=models.URLField(default=' ', help_text="Saisir l'URL liée à la première case à cocher sur le formulaire d'inscription", verbose_name='URL de la première case à cocher'),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='url_form_coche2_dest',
            field=models.URLField(default=' ', help_text="Saisir l'URL liée à la deuxième case à cocher sur le formulaire d'inscription", verbose_name='URL de la deuxième case à cocher'),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='url_form_coche3_dest',
            field=models.URLField(default=' ', help_text="Saisir l'URL liée à la troisième case à cocher sur le formulaire d'inscription", verbose_name='URL de la troisième case à cocher'),
        ),
    ]
