# Generated by Django 5.2.3 on 2025-12-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0018_alter_destination_data_flag_noanswer_visitor_dest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination_data',
            name='flag_NoAnswer_visitor_dest',
            field=models.CharField(choices=[('proposition', 'Annulation proposition'), ('demande', 'Annulation demande')], default='demande', help_text="Cocher l'action à effectuer suite à la non-réponse du visiteur", max_length=11, verbose_name='Action suite à la non-réponse du visiteur'),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='flag_reason_NoAnswer_greeter_dest',
            field=models.BooleanField(default=False, help_text='Cocher si le motif de la non proposition du Greeter est obligatoire', verbose_name='Demander le motif de la non-réponse du Greeter'),
        ),
    ]
