# Generated by Django 5.2.3 on 2025-12-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0019_alter_destination_data_flag_noanswer_visitor_dest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination_data',
            name='lib_url_form_coche1_dest_de',
            field=models.CharField(default=' ', help_text="Saisir le texte de l'URL liée à la première case à cocher sur le formulaire d'inscription", max_length=200, null=True, verbose_name="texte de l'URL de la première case à cocher"),
        ),
        migrations.AddField(
            model_name='destination_data',
            name='lib_url_form_coche1_dest_en_us',
            field=models.CharField(default=' ', help_text="Saisir le texte de l'URL liée à la première case à cocher sur le formulaire d'inscription", max_length=200, null=True, verbose_name="texte de l'URL de la première case à cocher"),
        ),
        migrations.AddField(
            model_name='destination_data',
            name='lib_url_form_coche1_dest_es',
            field=models.CharField(default=' ', help_text="Saisir le texte de l'URL liée à la première case à cocher sur le formulaire d'inscription", max_length=200, null=True, verbose_name="texte de l'URL de la première case à cocher"),
        ),
        migrations.AddField(
            model_name='destination_data',
            name='lib_url_form_coche1_dest_fr',
            field=models.CharField(default=' ', help_text="Saisir le texte de l'URL liée à la première case à cocher sur le formulaire d'inscription", max_length=200, null=True, verbose_name="texte de l'URL de la première case à cocher"),
        ),
        migrations.AddField(
            model_name='destination_data',
            name='lib_url_form_coche2_dest_de',
            field=models.CharField(default=' ', help_text="Saisir le texte de l'URL liée à la deuxième case à cocher sur le formulaire d'inscription", max_length=200, null=True, verbose_name="texte de l'URL de la deuxième case à cocher"),
        ),
        migrations.AddField(
            model_name='destination_data',
            name='lib_url_form_coche2_dest_en_us',
            field=models.CharField(default=' ', help_text="Saisir le texte de l'URL liée à la deuxième case à cocher sur le formulaire d'inscription", max_length=200, null=True, verbose_name="texte de l'URL de la deuxième case à cocher"),
        ),
        migrations.AddField(
            model_name='destination_data',
            name='lib_url_form_coche2_dest_es',
            field=models.CharField(default=' ', help_text="Saisir le texte de l'URL liée à la deuxième case à cocher sur le formulaire d'inscription", max_length=200, null=True, verbose_name="texte de l'URL de la deuxième case à cocher"),
        ),
        migrations.AddField(
            model_name='destination_data',
            name='lib_url_form_coche2_dest_fr',
            field=models.CharField(default=' ', help_text="Saisir le texte de l'URL liée à la deuxième case à cocher sur le formulaire d'inscription", max_length=200, null=True, verbose_name="texte de l'URL de la deuxième case à cocher"),
        ),
        migrations.AddField(
            model_name='destination_data',
            name='lib_url_form_coche3_dest_de',
            field=models.CharField(default=' ', help_text="Saisir le texte de l'URL liée à la troisième case à cocher sur le formulaire d'inscription", max_length=200, null=True, verbose_name="texte de l'URL de la troisième case à cocher"),
        ),
        migrations.AddField(
            model_name='destination_data',
            name='lib_url_form_coche3_dest_en_us',
            field=models.CharField(default=' ', help_text="Saisir le texte de l'URL liée à la troisième case à cocher sur le formulaire d'inscription", max_length=200, null=True, verbose_name="texte de l'URL de la troisième case à cocher"),
        ),
        migrations.AddField(
            model_name='destination_data',
            name='lib_url_form_coche3_dest_es',
            field=models.CharField(default=' ', help_text="Saisir le texte de l'URL liée à la troisième case à cocher sur le formulaire d'inscription", max_length=200, null=True, verbose_name="texte de l'URL de la troisième case à cocher"),
        ),
        migrations.AddField(
            model_name='destination_data',
            name='lib_url_form_coche3_dest_fr',
            field=models.CharField(default=' ', help_text="Saisir le texte de l'URL liée à la troisième case à cocher sur le formulaire d'inscription", max_length=200, null=True, verbose_name="texte de l'URL de la troisième case à cocher"),
        ),
        migrations.AddField(
            model_name='destination_data',
            name='libelle_form_coche1_dest_de',
            field=models.CharField(default=' ', help_text="Saisir le libellé de la première case à cocher sur le formulaire d'inscription", max_length=200, null=True, verbose_name='Libellé de la première case à cocher '),
        ),
        migrations.AddField(
            model_name='destination_data',
            name='libelle_form_coche1_dest_en_us',
            field=models.CharField(default=' ', help_text="Saisir le libellé de la première case à cocher sur le formulaire d'inscription", max_length=200, null=True, verbose_name='Libellé de la première case à cocher '),
        ),
        migrations.AddField(
            model_name='destination_data',
            name='libelle_form_coche1_dest_es',
            field=models.CharField(default=' ', help_text="Saisir le libellé de la première case à cocher sur le formulaire d'inscription", max_length=200, null=True, verbose_name='Libellé de la première case à cocher '),
        ),
        migrations.AddField(
            model_name='destination_data',
            name='libelle_form_coche1_dest_fr',
            field=models.CharField(default=' ', help_text="Saisir le libellé de la première case à cocher sur le formulaire d'inscription", max_length=200, null=True, verbose_name='Libellé de la première case à cocher '),
        ),
        migrations.AddField(
            model_name='destination_data',
            name='libelle_form_coche2_dest_de',
            field=models.CharField(default=' ', help_text="Saisir le libellé de la deuxième case à cocher sur le formulaire d'inscription", max_length=200, null=True, verbose_name='Libellé de la deuxième case à cocher '),
        ),
        migrations.AddField(
            model_name='destination_data',
            name='libelle_form_coche2_dest_en_us',
            field=models.CharField(default=' ', help_text="Saisir le libellé de la deuxième case à cocher sur le formulaire d'inscription", max_length=200, null=True, verbose_name='Libellé de la deuxième case à cocher '),
        ),
        migrations.AddField(
            model_name='destination_data',
            name='libelle_form_coche2_dest_es',
            field=models.CharField(default=' ', help_text="Saisir le libellé de la deuxième case à cocher sur le formulaire d'inscription", max_length=200, null=True, verbose_name='Libellé de la deuxième case à cocher '),
        ),
        migrations.AddField(
            model_name='destination_data',
            name='libelle_form_coche2_dest_fr',
            field=models.CharField(default=' ', help_text="Saisir le libellé de la deuxième case à cocher sur le formulaire d'inscription", max_length=200, null=True, verbose_name='Libellé de la deuxième case à cocher '),
        ),
        migrations.AddField(
            model_name='destination_data',
            name='libelle_form_coche3_dest_de',
            field=models.CharField(default=' ', help_text="Saisir le libellé de la troisième case à cocher sur le formulaire d'inscription", max_length=200, null=True, verbose_name='Libellé de la troisième case à cocher '),
        ),
        migrations.AddField(
            model_name='destination_data',
            name='libelle_form_coche3_dest_en_us',
            field=models.CharField(default=' ', help_text="Saisir le libellé de la troisième case à cocher sur le formulaire d'inscription", max_length=200, null=True, verbose_name='Libellé de la troisième case à cocher '),
        ),
        migrations.AddField(
            model_name='destination_data',
            name='libelle_form_coche3_dest_es',
            field=models.CharField(default=' ', help_text="Saisir le libellé de la troisième case à cocher sur le formulaire d'inscription", max_length=200, null=True, verbose_name='Libellé de la troisième case à cocher '),
        ),
        migrations.AddField(
            model_name='destination_data',
            name='libelle_form_coche3_dest_fr',
            field=models.CharField(default=' ', help_text="Saisir le libellé de la troisième case à cocher sur le formulaire d'inscription", max_length=200, null=True, verbose_name='Libellé de la troisième case à cocher '),
        ),
    ]
