# Generated by Django 5.2.3 on 2025-12-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0020_destination_data_lib_url_form_coche1_dest_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination_data',
            name='date_cg_mail_dest',
            field=models.DateField(blank=True, help_text="Saisir la date pour l'envoi du prochain courriel de Greet & Greet", null=True, verbose_name="Date d'envoi du prochain courriel C&G"),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='donation_proposal_dest',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Saisir la proposition de don pour la destination', max_digits=10, null=True, verbose_name='Proposition de don'),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='donation_text_dest',
            field=models.TextField(blank=True, help_text='Saisir le texte pour la demande de don sur le courriel du visiteur', max_length=500, null=True, verbose_name='Texte de la demande de don'),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='donation_text_dest_de',
            field=models.TextField(blank=True, help_text='Saisir le texte pour la demande de don sur le courriel du visiteur', max_length=500, null=True, verbose_name='Texte de la demande de don'),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='donation_text_dest_en_us',
            field=models.TextField(blank=True, help_text='Saisir le texte pour la demande de don sur le courriel du visiteur', max_length=500, null=True, verbose_name='Texte de la demande de don'),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='donation_text_dest_es',
            field=models.TextField(blank=True, help_text='Saisir le texte pour la demande de don sur le courriel du visiteur', max_length=500, null=True, verbose_name='Texte de la demande de don'),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='donation_text_dest_fr',
            field=models.TextField(blank=True, help_text='Saisir le texte pour la demande de don sur le courriel du visiteur', max_length=500, null=True, verbose_name='Texte de la demande de don'),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='flag_NoAnswer_visitor_dest',
            field=models.CharField(choices=[('demande', 'Annulation demande'), ('proposition', 'Annulation proposition')], default='demande', help_text="Cocher l'action à effectuer suite à la non-réponse du visiteur", max_length=11, verbose_name='Action suite à la non-réponse du visiteur'),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='googlemybusiness_dest',
            field=models.URLField(blank=True, help_text="Saisir l'URL de la page Google My Business de la destination", null=True, verbose_name='Google My Business de la destination'),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='libelle_social1_mail_dest',
            field=models.CharField(blank=True, help_text='Saisir le libellé du premier réseau social pour la destination', max_length=100, null=True, verbose_name='Libellé du premier réseau social'),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='libelle_social2_mail_dest',
            field=models.CharField(blank=True, help_text='Saisir le libellé du deuxième réseau social pour la destination', max_length=100, null=True, verbose_name='Libellé du deuxième réseau social'),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='nbre_participants_fermeture_dest',
            field=models.IntegerField(blank=True, default=0, help_text='Saisir le nombre de participants lors de la fermeture de la destination (0 fermeture totale)', null=True, verbose_name='Nombre de participants en cours de fermeture'),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='paypal_dest',
            field=models.URLField(blank=True, help_text="Saisir l'URL du compte Paypal de la destination", null=True, verbose_name='Paypal de la destination'),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='periode_mail_cg_dest',
            field=models.IntegerField(blank=True, default=7, help_text="Saisir la période d'envoi des courriels de Greet & Greet en jours", null=True, verbose_name="Période d'envoi des courriels C&G (en jours)"),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='tagline_mail_dest',
            field=models.CharField(blank=True, help_text='Saisir le tagline pour les courriels envoyés par la destination', max_length=150, null=True, verbose_name='Tagline pour les courriels'),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='tagline_mail_dest_de',
            field=models.CharField(blank=True, help_text='Saisir le tagline pour les courriels envoyés par la destination', max_length=150, null=True, verbose_name='Tagline pour les courriels'),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='tagline_mail_dest_en_us',
            field=models.CharField(blank=True, help_text='Saisir le tagline pour les courriels envoyés par la destination', max_length=150, null=True, verbose_name='Tagline pour les courriels'),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='tagline_mail_dest_es',
            field=models.CharField(blank=True, help_text='Saisir le tagline pour les courriels envoyés par la destination', max_length=150, null=True, verbose_name='Tagline pour les courriels'),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='tagline_mail_dest_fr',
            field=models.CharField(blank=True, help_text='Saisir le tagline pour les courriels envoyés par la destination', max_length=150, null=True, verbose_name='Tagline pour les courriels'),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='texte_avis_fermeture_dest',
            field=models.TextField(blank=True, help_text="Saisir le texte de l'avis de fermeture de la destination", max_length=1000, null=True, verbose_name="Texte de l'avis de fermeture"),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='texte_avis_fermeture_dest_de',
            field=models.TextField(blank=True, help_text="Saisir le texte de l'avis de fermeture de la destination", max_length=1000, null=True, verbose_name="Texte de l'avis de fermeture"),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='texte_avis_fermeture_dest_en_us',
            field=models.TextField(blank=True, help_text="Saisir le texte de l'avis de fermeture de la destination", max_length=1000, null=True, verbose_name="Texte de l'avis de fermeture"),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='texte_avis_fermeture_dest_es',
            field=models.TextField(blank=True, help_text="Saisir le texte de l'avis de fermeture de la destination", max_length=1000, null=True, verbose_name="Texte de l'avis de fermeture"),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='texte_avis_fermeture_dest_fr',
            field=models.TextField(blank=True, help_text="Saisir le texte de l'avis de fermeture de la destination", max_length=1000, null=True, verbose_name="Texte de l'avis de fermeture"),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='texte_avis_mail_dest',
            field=models.TextField(blank=True, help_text="Saisir le texte de l'avis en pied des courriels envoyés par la destination", max_length=1000, null=True, verbose_name="Texte de l'avis en pied des courriels"),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='texte_avis_mail_dest_de',
            field=models.TextField(blank=True, help_text="Saisir le texte de l'avis en pied des courriels envoyés par la destination", max_length=1000, null=True, verbose_name="Texte de l'avis en pied des courriels"),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='texte_avis_mail_dest_en_us',
            field=models.TextField(blank=True, help_text="Saisir le texte de l'avis en pied des courriels envoyés par la destination", max_length=1000, null=True, verbose_name="Texte de l'avis en pied des courriels"),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='texte_avis_mail_dest_es',
            field=models.TextField(blank=True, help_text="Saisir le texte de l'avis en pied des courriels envoyés par la destination", max_length=1000, null=True, verbose_name="Texte de l'avis en pied des courriels"),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='texte_avis_mail_dest_fr',
            field=models.TextField(blank=True, help_text="Saisir le texte de l'avis en pied des courriels envoyés par la destination", max_length=1000, null=True, verbose_name="Texte de l'avis en pied des courriels"),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='titre_avis_mail_dest',
            field=models.CharField(blank=True, help_text="Saisir le titre de l'avis en pied des courriels envoyés par la destination", max_length=100, null=True, verbose_name="Titre de l'avis en pied des courriels"),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='tripadvisor_dest',
            field=models.URLField(blank=True, help_text="Saisir l'URL de la page TripAdvisor de la destination", null=True, verbose_name='TripAdvisor de la destination'),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='url_social1_mail_dest',
            field=models.URLField(blank=True, help_text="Saisir l'URL du premier réseau social", null=True, verbose_name='URL du premier réseau social'),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='url_social2_mail_dest',
            field=models.URLField(blank=True, help_text="Saisir l'URL du deuxième réseau social", null=True, verbose_name='URL du deuxième réseau social'),
        ),
    ]
