# Generated by Django 5.2.3 on 2025-12-20 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0021_alter_destination_data_date_cg_mail_dest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='URL_retry_dest',
            field=models.URLField(default=None, help_text="Saisir l'URL de retour après la validation d'une demande", verbose_name='URL de retour'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='finance_dest',
            field=models.ForeignKey(help_text='Saisir le nom du gestionnaire financier de la destination', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_name_dest', to=settings.AUTH_USER_MODEL, verbose_name='Nom du gestionnaire financier'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='manager_dest',
            field=models.ForeignKey(help_text='Saisir le nom du manager de la destination', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_name_dest', to=settings.AUTH_USER_MODEL, verbose_name='Nom du manager'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='matcher_dest',
            field=models.ForeignKey(help_text='Saisir le nom du gestionnaire de la destination', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matcher_name_dest', to=settings.AUTH_USER_MODEL, verbose_name='Nom du gestionnaire'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='referent_dest',
            field=models.ForeignKey(help_text='Saisir le nom du référent de la destination', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referent_name_dest', to=settings.AUTH_USER_MODEL, verbose_name='Nom du référent'),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='flag_NoAnswer_visitor_dest',
            field=models.CharField(choices=[('proposition', 'Annulation proposition'), ('demande', 'Annulation demande')], default='demande', help_text="Cocher l'action à effectuer suite à la non-réponse du visiteur", max_length=11, verbose_name='Action suite à la non-réponse du visiteur'),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='param_comment_visitor_dest',
            field=models.TextField(blank=True, help_text="Saisir la présentation des commentaires pour le visiteur à l'inscription", max_length=1000, null=True, verbose_name='Présentation des commentaires pour le visiteur'),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='param_comment_visitor_dest_de',
            field=models.TextField(blank=True, help_text="Saisir la présentation des commentaires pour le visiteur à l'inscription", max_length=1000, null=True, verbose_name='Présentation des commentaires pour le visiteur'),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='param_comment_visitor_dest_en_us',
            field=models.TextField(blank=True, help_text="Saisir la présentation des commentaires pour le visiteur à l'inscription", max_length=1000, null=True, verbose_name='Présentation des commentaires pour le visiteur'),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='param_comment_visitor_dest_es',
            field=models.TextField(blank=True, help_text="Saisir la présentation des commentaires pour le visiteur à l'inscription", max_length=1000, null=True, verbose_name='Présentation des commentaires pour le visiteur'),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='param_comment_visitor_dest_fr',
            field=models.TextField(blank=True, help_text="Saisir la présentation des commentaires pour le visiteur à l'inscription", max_length=1000, null=True, verbose_name='Présentation des commentaires pour le visiteur'),
        ),
    ]
