# Generated by Django 5.2.3 on 2025-12-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0031_alter_destination_data_flag_noanswer_visitor_dest'),
    ]

    operations = [
        migrations.CreateModel(
            name='List_places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_places_dest', models.CharField(blank=True, default=' ', help_text='Saisir le lieu ou thème', max_length=500, null=True, verbose_name='Lieu ou thème ')),
            ],
        ),
        migrations.RemoveField(
            model_name='destination',
            name='list_places_dest_de',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='list_places_dest_en_us',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='list_places_dest_es',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='list_places_dest_fr',
        ),
    ]
