# Generated by Django 5.2.3 on 2025-12-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0032_list_places_remove_destination_list_places_dest_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_places',
            name='list_places_dest_de',
            field=models.CharField(blank=True, default=' ', help_text='Saisir le lieu ou thème', max_length=500, null=True, verbose_name='Lieu ou thème '),
        ),
        migrations.AddField(
            model_name='list_places',
            name='list_places_dest_en_us',
            field=models.CharField(blank=True, default=' ', help_text='Saisir le lieu ou thème', max_length=500, null=True, verbose_name='Lieu ou thème '),
        ),
        migrations.AddField(
            model_name='list_places',
            name='list_places_dest_es',
            field=models.CharField(blank=True, default=' ', help_text='Saisir le lieu ou thème', max_length=500, null=True, verbose_name='Lieu ou thème '),
        ),
        migrations.AddField(
            model_name='list_places',
            name='list_places_dest_fr',
            field=models.CharField(blank=True, default=' ', help_text='Saisir le lieu ou thème', max_length=500, null=True, verbose_name='Lieu ou thème '),
        ),
        migrations.RemoveField(
            model_name='destination',
            name='list_places_dest',
        ),
        migrations.AddField(
            model_name='destination',
            name='list_places_dest',
            field=models.ManyToManyField(blank=True, help_text='Sélectionner les lieux ou thèmes de la destination', to='destination.list_places', verbose_name='Lieux ou thèmes'),
        ),
    ]
