# Generated by Django 5.2.3 on 2026-01-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0033_list_places_list_places_dest_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination_data',
            name='flag_NoAnswer_visitor_dest',
            field=models.CharField(choices=[('proposition', 'Annulation proposition'), ('demande', 'Annulation demande')], default='demande', help_text="Cocher l'action à effectuer suite à la non-réponse du visiteur", max_length=11, verbose_name='Action suite à la non-réponse du visiteur'),
        ),
    ]
