# Generated by Django 5.2.3 on 2026-01-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0034_alter_destination_data_flag_noanswer_visitor_dest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='list_places_dest',
            field=models.ManyToManyField(blank=True, help_text='Sélectionner les lieux ou thèmes de la destination', related_name='destinations', to='destination.list_places', verbose_name='Lieux ou thèmes'),
        ),
        migrations.AlterField(
            model_name='destination_data',
            name='flag_NoAnswer_visitor_dest',
            field=models.CharField(choices=[('demande', 'Annulation demande'), ('proposition', 'Annulation proposition')], default='demande', help_text="Cocher l'action à effectuer suite à la non-réponse du visiteur", max_length=11, verbose_name='Action suite à la non-réponse du visiteur'),
        ),
    ]
