# Generated by Django 5.2.3 on 2025-12-20 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_alter_pays_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Greeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_greeter', models.CharField(default='', help_text='Saisir le statut du Greeter', max_length=15, verbose_name='Statut')),
                ('genre_greeter', models.CharField(default='', help_text='Saisir le genre du Greeter', max_length=1, verbose_name='Genre')),
                ('adress1_greeter', models.CharField(default='', help_text="Saisir l'adresse du Greeter", max_length=50, verbose_name='Adresse 1')),
                ('adress2_greeter', models.CharField(blank=True, default='', help_text="Saisir l'adresse complémentaire du Greeter", max_length=50, null=True, verbose_name='Adresse 2')),
                ('postalcode_greeter', models.CharField(default='', help_text='Saisir le code postal du Greeter', max_length=5, verbose_name='Code postal')),
                ('city_greeter', models.CharField(default='', help_text='Saisir la ville du Greeter', max_length=50, verbose_name='Ville')),
                ('country_greeter', models.CharField(default='', help_text='Saisir le pays du Greeter', max_length=50, verbose_name='Pays')),
                ('office_phone_greeter', models.CharField(default='', help_text='Saisir le numéro de téléphone du bureau du Greeter', max_length=20, verbose_name='Téléphone bureau')),
                ('landline_phone_greeter', models.CharField(default='', help_text='Saisir le numéro de téléphone portable du Greeter', max_length=20, verbose_name='Téléphone portable')),
                ('whatsapp_phone_greeter', models.CharField(default='', help_text='Saisir le numéro de téléphone whatsapp du Greeter', max_length=20, verbose_name='Téléphone whatsapp')),
                ('experiences_greeters', models.CharField(default='', help_text='Saisir les expériences du Greeter', max_length=300, verbose_name='Expériences')),
                ('photo', models.ImageField(default='photos_profil/default.jpg', help_text='Taille : 200 px *200 px', upload_to='photos_profil/', verbose_name='Photo de profil')),
                ('bio_greeter', models.TextField(default='', help_text='Saisir la biographie du Greeter', max_length=1500, verbose_name='Biographie')),
                ('handicap_greeter', models.BooleanField(default=False, help_text='Saisir si le Greeter accepte des balades avec des personnes ayant un handicap', verbose_name='Accepte des balades avec des personnes ayant un handicap')),
                ('visibily_greeter', models.BooleanField(default=False, help_text='Saisir si le Greeter accepte que sa photo soit transmise au visiteur', verbose_name='Accepte que sa photo soit transmise au visiteur')),
                ('langues_parlées_greeter', models.CharField(default='', help_text='Saisir les langues parlées du Greeter', max_length=100, verbose_name='Langues parlées')),
                ('max_participants_greeter', models.IntegerField(default=6, help_text='Saisir le nombre maximum de participants accepté par le Greeter', verbose_name='Nombre maximum de participants')),
                ('disponibility_day_greeter', models.CharField(default='', help_text='Saisir les jours de disponibilité du Greeter', max_length=100, verbose_name='Jours de disponibilité')),
                ('disponibility_time_greeter', models.CharField(default='', help_text='Saisir les heures de disponibilité du Greeter', max_length=100, verbose_name='Heures de disponibilité')),
                ('frequency_greeter', models.IntegerField(default=1, help_text="Saisir l'intervalle en jours entre deux balades", verbose_name='Intervalle en jours entre deux balades')),
                ('comments_greeter', models.TextField(default='', help_text='Saisir les commentaires du Greeter', max_length=1500, verbose_name='Commentaires')),
                ('interest_greeter', models.CharField(default='', help_text="Saisir les centres d'intérêts du Greeter", max_length=300, verbose_name='Intérêts')),
                ('list_places_greeter', models.CharField(default='', help_text='Saisir les cethèmes ou lieux du Greeter', max_length=300, verbose_name='Thèmes ou lieux')),
                ('arrival_greeter', models.DateField(help_text="Saisir la date d'arrivée du Greeter", verbose_name="Date d'arrivée")),
                ('departure_greeter', models.DateField(help_text='Saisir la date de départ du Greeter', verbose_name='Date de départ')),
                ('modif_greeter', models.DateTimeField(auto_now=True, help_text='Saisir la date de dernière modification du Greeter', null=True, verbose_name='Date de dernière modification')),
                ('name_correcteur_greeter', models.CharField(blank=True, default='', help_text='Saisir le nom du correcteur', max_length=30, null=True, verbose_name='Nom du correcteur')),
                ('correction_greeter', models.TextField(blank=True, default='', help_text='Saisir les corrections de la fiche Greeter', max_length=1000, null=True, verbose_name='Corrections de la fiche Greeter')),
                ('age_greeter', models.ForeignKey(help_text="Saisir la tranche d'âge du Greeter", on_delete=django.db.models.deletion.PROTECT, to='core.trancheage', verbose_name="Tranche d'âge")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GreeterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langue_greet_type', models.CharField(default='', help_text='Saisir la langue parlée du greet-type', max_length=20, verbose_name='Langue du greet-type')),
                ('titre_greet_type', models.CharField(default='', help_text='Saisir le titre du greet-type dans la langue du greet-type', max_length=50, verbose_name='Titre du greet-type')),
                ('list_places_greet_type', models.CharField(default='', help_text='Saisir les cethèmes ou lieux du greet-type', max_length=300, verbose_name='Thèmes ou lieux')),
                ('rv_greet_type', models.CharField(default='', help_text='Saisir le lieu du rendezz-vous', max_length=100, verbose_name='Lieu du rendezz-vous')),
                ('maps_greet_type', models.URLField(blank=True, default='', help_text='Saisir le lien Google Maps du lieu de rendez-vous', null=True, verbose_name='Lien Google Maps')),
                ('description_greet_type', models.TextField(default='', help_text='Saisir la description du greet-type', max_length=500, verbose_name='Description')),
                ('photo_greet_type', models.ImageField(default='photos_profil/default.jpg', help_text='Taille : 1200 px * 900 px', upload_to='photos_profil/', verbose_name='Photo du greet-type')),
                ('greeter_greet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='greet_types', to='greeters.greeter')),
            ],
        ),
        migrations.CreateModel(
            name='Indisponibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_indisponibility', models.DateField(blank=True, help_text="Saisir la date de début de l'indisponibilité", null=True, verbose_name='Date de début')),
                ('end_date_indisponibility', models.DateField(blank=True, help_text="Saisir la date de fin de l'indisponibilité", null=True, verbose_name='Date de fin')),
                ('comments_indisponibility', models.CharField(blank=True, help_text="Saisir les commentaires de l'indisponibilité", max_length=255, null=True, verbose_name='Commentaires')),
                ('greeter_indisponibility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indisponibilities', to='greeters.greeter')),
            ],
            options={
                'verbose_name': 'Indisponibilité',
                'verbose_name_plural': 'Indisponibilités',
            },
        ),
    ]
