# Generated by Django 5.2.3 on 2025-12-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greeters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greeter',
            name='genre_greeter',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('X', 'Autre')], default='X', help_text='Saisir le genre du Greeter', max_length=1, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='greeter',
            name='statut_greeter',
            field=models.CharField(choices=[('Drafts', 'Brouillon'), ('Active', 'Actif'), ('Inactive', 'Inactif'), ('Désactivated', 'Désactivé')], default='Drafts', help_text='Saisir le statut du Greeter', max_length=15, verbose_name='Statut'),
        ),
    ]
