# Generated by Django 5.2.3 on 2026-01-11 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('greeters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='greeter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='greetertype',
            name='greeter_greet_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='greet_types', to='greeters.greeter'),
        ),
        migrations.AddField(
            model_name='indisponibility',
            name='greeter_indisponibility',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='indisponibilities', to='greeters.greeter'),
        ),
    ]
