# Generated by Django 5.2.3 on 2025-12-20 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_pays_options'),
        ('greeters', '0002_alter_greeter_genre_greeter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greeter',
            name='country_greeter',
            field=models.ForeignKey(default='', help_text='Saisir le pays du Greeter', max_length=50, on_delete=django.db.models.deletion.PROTECT, to='core.pays', verbose_name='Pays'),
        ),
        migrations.RemoveField(
            model_name='greeter',
            name='langues_parlées_greeter',
        ),
        migrations.AddField(
            model_name='greeter',
            name='langues_parlées_greeter',
            field=models.ManyToManyField(blank=True, default='', help_text='Saisir les langues parlées du Greeter', max_length=100, to='core.langueparlee', verbose_name='Langues parlées'),
        ),
    ]
