# Generated by Django 5.2.3 on 2026-01-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0002_cluster_admin_alt_cluster_cluster_admin_cluster_and_more'),
        ('core', '0001_initial'),
        ('destination', '0003_alter_destination_data_flag_noanswer_visitor_dest'),
        ('greeters', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greeter',
            name='disponibility_time_greeter',
            field=models.ManyToManyField(blank=True, default='', help_text='Saisir les périodes de disponibilité en journée du Greeter', max_length=100, to='core.periode', verbose_name='Disponibilité en journée'),
        ),
        migrations.AlterField(
            model_name='greeter',
            name='interest_greeter',
            field=models.ManyToManyField(blank=True, help_text="Saisir les centres d'intérêts du Greeter", to='cluster.interestcenter', verbose_name='Intérêts'),
        ),
        migrations.AlterField(
            model_name='greeter',
            name='list_places_greeter',
            field=models.ManyToManyField(blank=True, help_text='Saisir les cethèmes ou lieux du Greeter', to='destination.list_places', verbose_name='Thèmes ou lieux'),
        ),
    ]
