# Generated by Django 5.2.3 on 2025-12-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_pays_options'),
        ('greeters', '0003_alter_greeter_country_greeter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greeter',
            name='disponibility_time_greeter',
        ),
        migrations.AddField(
            model_name='greeter',
            name='disponibility_time_greeter',
            field=models.ManyToManyField(default='', help_text='Saisir les périodes de disponibilité en journée du Greeter', max_length=100, to='core.periode', verbose_name='Disponibilité en journée'),
        ),
    ]
