# Generated by Django 5.2.3 on 2026-02-04 11:32

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('greeters', '0003_alter_greeter_disponibility_time_greeter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greeter',
            name='age_greeter',
            field=models.ForeignKey(help_text="Saisir la tranche d'âge du Greeter", limit_choices_to={'id__gt': 2}, on_delete=django.db.models.deletion.PROTECT, to='core.trancheage', verbose_name="Tranche d'âge"),
        ),
        migrations.AlterField(
            model_name='greeter',
            name='disponibility_day_greeter',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi'), ('Dimanche', 'Dimanche')], default='Lundi, Mardi, Mercredi, Jeudi, Vendredi, Samedi, Dimanche', help_text='Saisir les jours de disponibilité du Greeter', max_length=100, verbose_name='Jours de disponibilité'),
        ),
    ]
