# Generated by Django 5.2.3 on 2026-02-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greeters', '0004_alter_greeter_age_greeter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='greeter',
            name='begin_indisponibility',
            field=models.DateField(blank=True, help_text="Saisir la date de début d'indisponibilité du Greeter", null=True, verbose_name="Date de début d'indisponibilité"),
        ),
        migrations.AddField(
            model_name='greeter',
            name='end_indisponibility',
            field=models.DateField(blank=True, help_text="Saisir la date de fin d'indisponibilité du Greeter", null=True, verbose_name="Date de fin d'indisponibilité"),
        ),
        migrations.AddField(
            model_name='greeter',
            name='indisponibilty',
            field=models.BooleanField(default=False, help_text='Saisir la disponibilité du Greeter', verbose_name='Disponibilité'),
        ),
    ]
