# Generated by Django 5.2.3 on 2025-12-20 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greeters', '0004_remove_greeter_disponibility_time_greeter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indisponibility',
            name='greeter_indisponibility',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='indisponibilities', to='greeters.greeter'),
        ),
    ]
