# Generated by Django 5.2.3 on 2026-02-11 07:59

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0002_cluster_admin_alt_cluster_cluster_admin_cluster_and_more'),
        ('core', '0001_initial'),
        ('destination', '0005_alter_destination_country_dest'),
        ('greeters', '0005_greeter_begin_indisponibility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greeter',
            name='disponibility_day_greeter',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi'), ('Dimanche', 'Dimanche')], default='Lundi, Mardi, Mercredi, Jeudi, Vendredi, Samedi, Dimanche', help_text='Cocher les jours de disponibilité du Greeter', max_length=100, verbose_name='Jours de disponibilité'),
        ),
        migrations.AlterField(
            model_name='greeter',
            name='disponibility_time_greeter',
            field=models.ManyToManyField(default='', help_text='Cocher les périodes de disponibilité en journée du Greeter', max_length=100, to='core.periode', verbose_name='Disponibilité en journée'),
        ),
        migrations.AlterField(
            model_name='greeter',
            name='experiences_greeters',
            field=models.ManyToManyField(help_text='Cocher les expériences de Greeter', to='cluster.experience_greeter', verbose_name='Expériences de Greeter'),
        ),
        migrations.AlterField(
            model_name='greeter',
            name='indisponibilty',
            field=models.BooleanField(default=False, help_text='Cocher si le Greeter est actuellement indisponible', verbose_name='Indisponible'),
        ),
        migrations.AlterField(
            model_name='greeter',
            name='interest_greeter',
            field=models.ManyToManyField(help_text="Cocher les centres d'intérêts du Greeter", to='cluster.interestcenter', verbose_name='Intérêts'),
        ),
        migrations.AlterField(
            model_name='greeter',
            name='list_places_greeter',
            field=models.ManyToManyField(help_text='Cocher les cethèmes ou lieux du Greeter', to='destination.list_places', verbose_name='Thèmes ou lieux'),
        ),
    ]
