# Generated by Django 5.2.3 on 2025-12-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greeters', '0005_alter_indisponibility_greeter_indisponibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greeter',
            name='office_phone_greeter',
        ),
        migrations.AlterField(
            model_name='greeter',
            name='comments_greeter',
            field=models.TextField(blank=True, default='', help_text='Saisir les commentaires du Greeter', max_length=1500, null=True, verbose_name='Commentaires'),
        ),
        migrations.AlterField(
            model_name='greeter',
            name='departure_greeter',
            field=models.DateField(blank=True, help_text='Saisir la date de départ du Greeter', null=True, verbose_name='Date de départ'),
        ),
        migrations.AlterField(
            model_name='greeter',
            name='disponibility_day_greeter',
            field=models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi'), ('Dimanche', 'Dimanche')], default='Lundi, Mardi, Mercredi, Jeudi, Vendredi, Samedi, Dimanche', help_text='Saisir les jours de disponibilité du Greeter', max_length=100, verbose_name='Jours de disponibilité'),
        ),
        migrations.AlterField(
            model_name='greeter',
            name='landline_phone_greeter',
            field=models.CharField(blank=True, default='', help_text='Saisir le numéro de téléphone fixe du Greeter', max_length=20, null=True, verbose_name='Téléphone fixe'),
        ),
        migrations.AlterField(
            model_name='greeter',
            name='statut_greeter',
            field=models.CharField(choices=[('Drafts', 'Brouillon'), ('Active', 'Actif'), ('Inactive', 'Inactif'), ('Archived', 'Archivé')], default='Drafts', help_text='Saisir le statut du Greeter', max_length=15, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='greeter',
            name='whatsapp_phone_greeter',
            field=models.CharField(blank=True, default='', help_text='Saisir le numéro de téléphone whatsapp du Greeter', max_length=20, null=True, verbose_name='Téléphone whatsapp'),
        ),
    ]
