# Generated by Django 5.2.3 on 2025-12-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_pays_options'),
        ('greeters', '0006_remove_greeter_office_phone_greeter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greeter',
            name='disponibility_time_greeter',
            field=models.ManyToManyField(blank=True, default='', help_text='Saisir les périodes de disponibilité en journée du Greeter', max_length=100, null=True, to='core.periode', verbose_name='Disponibilité en journée'),
        ),
    ]
