# Generated by Django 5.2.3 on 2026-03-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0007_alter_destination_data_flag_noanswer_visitor_dest'),
        ('greeters', '0006_alter_greeter_disponibility_day_greeter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greeter',
            name='list_places_greeter',
            field=models.ManyToManyField(help_text='Cocher les thèmes ou lieux du Greeter', to='destination.list_places', verbose_name='Thèmes ou lieux'),
        ),
    ]
