# Generated by Django 5.2.3 on 2026-01-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0022_interestcenter_interest_center_de_and_more'),
        ('greeters', '0007_alter_greeter_disponibility_time_greeter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greeter',
            name='experiences_greeters',
        ),
        migrations.AddField(
            model_name='greeter',
            name='experiences_greeters',
            field=models.ManyToManyField(blank=True, help_text='Saisir les expériences de Greeter', to='cluster.experience_greeter', verbose_name='Expériences de Greeter'),
        ),
    ]
