# Generated by Django 5.2.3 on 2025-09-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_cluster', models.CharField(default=' ', max_length=5, unique=True, verbose_name='Code')),
                ('name_cluster', models.CharField(default=' ', max_length=30, verbose_name='Nom')),
                ('adress_cluster', models.CharField(default=' ', max_length=100, verbose_name='Adresse')),
                ('desc_cluster', models.TextField(default=' ', help_text='Décrire les zones géographiques du cluster', max_length=500, verbose_name='Description')),
                ('paypal_cluster', models.URLField(default=' ', help_text='URL du compte Paypal du cluster', verbose_name='Paypal du cluster')),
                ('country_admin_cluster', models.CharField(default=' ', max_length=30, verbose_name='Pays')),
                ('country_admin_alt_cluster', models.CharField(blank=True, default=' ', max_length=30, verbose_name='Pays')),
                ('param_nbr_part_cluster', models.IntegerField(default=6, help_text='Nombre maximun de participantsvisiteurs pour le cluster', verbose_name='Nombre maximun de participants')),
                ('lang_com', models.CharField(choices=[('en-us', 'English (US)'), ('fr', 'Français'), ('de', 'Deutsch'), ('es', 'Español')], default='fr', help_text='Langue de communication de base du cluster', max_length=5, verbose_name='Langue de communication')),
                ('backup_mails_cluster', models.EmailField(default=' ', help_text="Adresse de sauvegarde des courriels générés sur l'ensemnble du cluster", max_length=254, verbose_name='Adresse  de sauvegarde des courriels')),
                ('url_biblio_cluster', models.URLField(blank=True, default=' ', verbose_name='URL de la bibliothèque')),
                ('url_biblio_Greeter_cluster', models.URLField(blank=True, default=' ', verbose_name='URL de la bibliothèque Cluster du Greeter')),
                ('list_experience_cluster', models.CharField(default=' ', help_text='Saisir les expériences du Greeter', max_length=500, verbose_name='Liste des expériences')),
                ('list_experience_cluster_en_us', models.CharField(default=' ', help_text='Saisir les expériences du Greeter', max_length=500, null=True, verbose_name='Liste des expériences')),
                ('list_experience_cluster_fr', models.CharField(default=' ', help_text='Saisir les expériences du Greeter', max_length=500, null=True, verbose_name='Liste des expériences')),
                ('list_experience_cluster_de', models.CharField(default=' ', help_text='Saisir les expériences du Greeter', max_length=500, null=True, verbose_name='Liste des expériences')),
                ('list_experience_cluster_es', models.CharField(default=' ', help_text='Saisir les expériences du Greeter', max_length=500, null=True, verbose_name='Liste des expériences')),
                ('profil_interet_cluster', models.CharField(default=' ', help_text="Saisir les centres d'intérêts des visiteurs et Greeter", max_length=500, verbose_name="Profil d'intérêt")),
                ('profil_interet_cluster_en_us', models.CharField(default=' ', help_text="Saisir les centres d'intérêts des visiteurs et Greeter", max_length=500, null=True, verbose_name="Profil d'intérêt")),
                ('profil_interet_cluster_fr', models.CharField(default=' ', help_text="Saisir les centres d'intérêts des visiteurs et Greeter", max_length=500, null=True, verbose_name="Profil d'intérêt")),
                ('profil_interet_cluster_de', models.CharField(default=' ', help_text="Saisir les centres d'intérêts des visiteurs et Greeter", max_length=500, null=True, verbose_name="Profil d'intérêt")),
                ('profil_interet_cluster_es', models.CharField(default=' ', help_text="Saisir les centres d'intérêts des visiteurs et Greeter", max_length=500, null=True, verbose_name="Profil d'intérêt")),
                ('reason_no_reply_greeter_cluster', models.CharField(default=' ', help_text='Saisir les raisons de non réponse du Greeter', max_length=500, verbose_name='Raison de non réponse du Greeter')),
                ('reason_no_reply_greeter_cluster_en_us', models.CharField(default=' ', help_text='Saisir les raisons de non réponse du Greeter', max_length=500, null=True, verbose_name='Raison de non réponse du Greeter')),
                ('reason_no_reply_greeter_cluster_fr', models.CharField(default=' ', help_text='Saisir les raisons de non réponse du Greeter', max_length=500, null=True, verbose_name='Raison de non réponse du Greeter')),
                ('reason_no_reply_greeter_cluster_de', models.CharField(default=' ', help_text='Saisir les raisons de non réponse du Greeter', max_length=500, null=True, verbose_name='Raison de non réponse du Greeter')),
                ('reason_no_reply_greeter_cluster_es', models.CharField(default=' ', help_text='Saisir les raisons de non réponse du Greeter', max_length=500, null=True, verbose_name='Raison de non réponse du Greeter')),
                ('reason_no_reply_visitor_cluster', models.CharField(default=' ', help_text='Saisir les raisons de non réponse du visiteur', max_length=500, verbose_name='Raison de non réponse du visiteur')),
                ('reason_no_reply_visitor_cluster_en_us', models.CharField(default=' ', help_text='Saisir les raisons de non réponse du visiteur', max_length=500, null=True, verbose_name='Raison de non réponse du visiteur')),
                ('reason_no_reply_visitor_cluster_fr', models.CharField(default=' ', help_text='Saisir les raisons de non réponse du visiteur', max_length=500, null=True, verbose_name='Raison de non réponse du visiteur')),
                ('reason_no_reply_visitor_cluster_de', models.CharField(default=' ', help_text='Saisir les raisons de non réponse du visiteur', max_length=500, null=True, verbose_name='Raison de non réponse du visiteur')),
                ('reason_no_reply_visitor_cluster_es', models.CharField(default=' ', help_text='Saisir les raisons de non réponse du visiteur', max_length=500, null=True, verbose_name='Raison de non réponse du visiteur')),
                ('list_notoriety_cluster', models.CharField(default=' ', help_text="Saisir les raisons d'un visiteur de connaître  l'existence des Greeters", max_length=500, verbose_name='Liste des notoriétés')),
                ('list_notoriety_cluster_en_us', models.CharField(default=' ', help_text="Saisir les raisons d'un visiteur de connaître  l'existence des Greeters", max_length=500, null=True, verbose_name='Liste des notoriétés')),
                ('list_notoriety_cluster_fr', models.CharField(default=' ', help_text="Saisir les raisons d'un visiteur de connaître  l'existence des Greeters", max_length=500, null=True, verbose_name='Liste des notoriétés')),
                ('list_notoriety_cluster_de', models.CharField(default=' ', help_text="Saisir les raisons d'un visiteur de connaître  l'existence des Greeters", max_length=500, null=True, verbose_name='Liste des notoriétés')),
                ('list_notoriety_cluster_es', models.CharField(default=' ', help_text="Saisir les raisons d'un visiteur de connaître  l'existence des Greeters", max_length=500, null=True, verbose_name='Liste des notoriétés')),
            ],
        ),
    ]
