# Generated by Django 5.2.3 on 2026-01-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_cluster', models.CharField(default=' ', max_length=5, unique=True, verbose_name='Code')),
                ('name_cluster', models.CharField(default=' ', max_length=30, verbose_name='Nom')),
                ('statut_cluster', models.CharField(choices=[('Drafts', 'Brouillon'), ('Active', 'Actif'), ('Inactive', 'Inactif'), ('Désactivated', 'Désactivé')], default='Drafts', help_text='Saisir le statut du cluster', max_length=15, verbose_name='Statut')),
                ('adress_cluster', models.CharField(default=' ', max_length=100, verbose_name='Adresse')),
                ('desc_cluster', models.TextField(default=' ', help_text='Décrire les zones géographiques du cluster', max_length=500, verbose_name='Description')),
                ('paypal_cluster', models.URLField(default=' ', help_text='URL du compte Paypal du cluster', verbose_name='Paypal du cluster')),
                ('param_nbr_part_cluster', models.IntegerField(default=6, help_text='Nombre maximun de visiteurs pour le cluster', verbose_name='Nombre maximun de participants')),
                ('backup_mails_cluster', models.EmailField(default=' ', help_text="Adresse de sauvegarde des courriels générés sur l'ensemnble du cluster", max_length=254, verbose_name='Adresse  de sauvegarde des courriels')),
                ('url_biblio_cluster', models.URLField(blank=True, default=' ', help_text="Saisir l'URL de la bibliothèque pour les destinations", verbose_name='URL de la bibliothèque Cluster des destinations')),
                ('url_biblio_Greeter_cluster', models.URLField(blank=True, default=' ', help_text="Saisir l'URL de la bibliothèque pour les Greeter", verbose_name='URL de la bibliothèque Cluster des Greeter')),
            ],
        ),
        migrations.CreateModel(
            name='Experience_Greeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_greeter', models.CharField(default="Pas d'expérience", help_text="Saisir l'expérience du Greeter", max_length=100, verbose_name='Expérience')),
                ('experience_greeter_en_us', models.CharField(default="Pas d'expérience", help_text="Saisir l'expérience du Greeter", max_length=100, null=True, verbose_name='Expérience')),
                ('experience_greeter_fr', models.CharField(default="Pas d'expérience", help_text="Saisir l'expérience du Greeter", max_length=100, null=True, verbose_name='Expérience')),
                ('experience_greeter_de', models.CharField(default="Pas d'expérience", help_text="Saisir l'expérience du Greeter", max_length=100, null=True, verbose_name='Expérience')),
                ('experience_greeter_es', models.CharField(default="Pas d'expérience", help_text="Saisir l'expérience du Greeter", max_length=100, null=True, verbose_name='Expérience')),
            ],
        ),
        migrations.CreateModel(
            name='InterestCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_center', models.CharField(max_length=100, verbose_name="Centre d'intérêt")),
                ('interest_center_en_us', models.CharField(max_length=100, null=True, verbose_name="Centre d'intérêt")),
                ('interest_center_fr', models.CharField(max_length=100, null=True, verbose_name="Centre d'intérêt")),
                ('interest_center_de', models.CharField(max_length=100, null=True, verbose_name="Centre d'intérêt")),
                ('interest_center_es', models.CharField(max_length=100, null=True, verbose_name="Centre d'intérêt")),
            ],
        ),
        migrations.CreateModel(
            name='Notoriety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notoriety', models.CharField(max_length=100, verbose_name='Notoriété')),
                ('notoriety_en_us', models.CharField(max_length=100, null=True, verbose_name='Notoriété')),
                ('notoriety_fr', models.CharField(max_length=100, null=True, verbose_name='Notoriété')),
                ('notoriety_de', models.CharField(max_length=100, null=True, verbose_name='Notoriété')),
                ('notoriety_es', models.CharField(max_length=100, null=True, verbose_name='Notoriété')),
            ],
        ),
        migrations.CreateModel(
            name='Reason_No_Response_Greeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_no_reply_greeter', models.CharField(max_length=100, verbose_name='Raison de non réponse du Greeter')),
                ('reason_no_reply_greeter_en_us', models.CharField(max_length=100, null=True, verbose_name='Raison de non réponse du Greeter')),
                ('reason_no_reply_greeter_fr', models.CharField(max_length=100, null=True, verbose_name='Raison de non réponse du Greeter')),
                ('reason_no_reply_greeter_de', models.CharField(max_length=100, null=True, verbose_name='Raison de non réponse du Greeter')),
                ('reason_no_reply_greeter_es', models.CharField(max_length=100, null=True, verbose_name='Raison de non réponse du Greeter')),
            ],
        ),
        migrations.CreateModel(
            name='Reason_No_Response_Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_no_reply_visitor', models.CharField(max_length=100, verbose_name='Raison de non réponse du visiteur')),
                ('reason_no_reply_visitor_en_us', models.CharField(max_length=100, null=True, verbose_name='Raison de non réponse du visiteur')),
                ('reason_no_reply_visitor_fr', models.CharField(max_length=100, null=True, verbose_name='Raison de non réponse du visiteur')),
                ('reason_no_reply_visitor_de', models.CharField(max_length=100, null=True, verbose_name='Raison de non réponse du visiteur')),
                ('reason_no_reply_visitor_es', models.CharField(max_length=100, null=True, verbose_name='Raison de non réponse du visiteur')),
            ],
        ),
    ]
