# Generated by Django 5.2.3 on 2026-01-11 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='admin_alt_cluster',
            field=models.ForeignKey(blank=True, help_text="Saisir l'administrateur alternatif parmi les utilisateurs ou en créer un", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_alt_cluster', to=settings.AUTH_USER_MODEL, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='admin_cluster',
            field=models.ForeignKey(blank=True, help_text="Saisir l'administrateur parmi les utilisateurs ou en créer un", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_cluster', to=settings.AUTH_USER_MODEL, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='country_admin_alt_cluster',
            field=models.ForeignKey(blank=True, help_text="Saisir le pays de l'admnistrateur alternatif", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_admin_alt_cluster', to='core.pays', verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='country_admin_cluster',
            field=models.ForeignKey(blank=True, help_text="Saisir le pays de l'administrateur", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_admin_cluster', to='core.pays', verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='experience_greeter',
            field=models.ManyToManyField(related_name='list_experience_cluster', to='cluster.experience_greeter'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='interest_center',
            field=models.ManyToManyField(related_name='profil_interet_cluster', to='cluster.interestcenter'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='langs_com',
            field=models.ManyToManyField(help_text='Sélectionner les langues de communication du cluster', related_name='langs_com', to='core.language_communication', verbose_name='Langues de communication'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='notoriety',
            field=models.ManyToManyField(related_name='list_notoriety_cluster', to='cluster.notoriety'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='reason_no_reply_greeter',
            field=models.ManyToManyField(related_name='reason_no_reply_greeter_cluster', to='cluster.reason_no_response_greeter'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='reason_no_reply_visitor',
            field=models.ManyToManyField(related_name='reason_no_reply_visitor_cluster', to='cluster.reason_no_response_visitor'),
        ),
    ]
