# Generated by Django 5.2.3 on 2025-09-19 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cluster', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='admin_alt_cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_alt_cluster', to=settings.AUTH_USER_MODEL, verbose_name='NomAdministrateur alternatif'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='admin_cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_cluster', to=settings.AUTH_USER_MODEL, verbose_name='Administrateur principal'),
        ),
    ]
