# Generated by Django 5.2.3 on 2025-09-22 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='admin_alt_cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_alt_cluster', to=settings.AUTH_USER_MODEL, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='admin_cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_cluster', to=settings.AUTH_USER_MODEL, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='url_biblio_Greeter_cluster',
            field=models.URLField(blank=True, default=' ', help_text="Saisir l'URL de la bibliothèque pour les Greeter", verbose_name='URL de la bibliothèque Cluster du Greeter'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='url_biblio_cluster',
            field=models.URLField(blank=True, default=' ', help_text="Saisir l'URL de la bibliothèque pour les destinations", verbose_name='URL de la bibliothèque'),
        ),
    ]
