# Generated by Django 5.2.3 on 2025-09-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0003_alter_cluster_admin_alt_cluster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='list_experience_cluster',
            field=models.CharField(default=' ', help_text='Saisir les expériences du Greeter', max_length=500, verbose_name='Expériences des Greeters'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='list_experience_cluster_de',
            field=models.CharField(default=' ', help_text='Saisir les expériences du Greeter', max_length=500, null=True, verbose_name='Expériences des Greeters'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='list_experience_cluster_en_us',
            field=models.CharField(default=' ', help_text='Saisir les expériences du Greeter', max_length=500, null=True, verbose_name='Expériences des Greeters'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='list_experience_cluster_es',
            field=models.CharField(default=' ', help_text='Saisir les expériences du Greeter', max_length=500, null=True, verbose_name='Expériences des Greeters'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='list_experience_cluster_fr',
            field=models.CharField(default=' ', help_text='Saisir les expériences du Greeter', max_length=500, null=True, verbose_name='Expériences des Greeters'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='param_nbr_part_cluster',
            field=models.IntegerField(default=7, help_text='Nombre maximun de visiteurs pour le cluster', verbose_name='Nombre maximun de participants'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='profil_interet_cluster',
            field=models.CharField(default=' ', help_text="Saisir les centres d'intérêts des visiteurs et Greeter", max_length=500, verbose_name="Centres d'intérêt"),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='profil_interet_cluster_de',
            field=models.CharField(default=' ', help_text="Saisir les centres d'intérêts des visiteurs et Greeter", max_length=500, null=True, verbose_name="Centres d'intérêt"),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='profil_interet_cluster_en_us',
            field=models.CharField(default=' ', help_text="Saisir les centres d'intérêts des visiteurs et Greeter", max_length=500, null=True, verbose_name="Centres d'intérêt"),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='profil_interet_cluster_es',
            field=models.CharField(default=' ', help_text="Saisir les centres d'intérêts des visiteurs et Greeter", max_length=500, null=True, verbose_name="Centres d'intérêt"),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='profil_interet_cluster_fr',
            field=models.CharField(default=' ', help_text="Saisir les centres d'intérêts des visiteurs et Greeter", max_length=500, null=True, verbose_name="Centres d'intérêt"),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='reason_no_reply_greeter_cluster',
            field=models.CharField(default=' ', help_text='Saisir les raisons de non réponse du Greeter', max_length=500, verbose_name='Raisons de non réponse du Greeter'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='reason_no_reply_greeter_cluster_de',
            field=models.CharField(default=' ', help_text='Saisir les raisons de non réponse du Greeter', max_length=500, null=True, verbose_name='Raisons de non réponse du Greeter'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='reason_no_reply_greeter_cluster_en_us',
            field=models.CharField(default=' ', help_text='Saisir les raisons de non réponse du Greeter', max_length=500, null=True, verbose_name='Raisons de non réponse du Greeter'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='reason_no_reply_greeter_cluster_es',
            field=models.CharField(default=' ', help_text='Saisir les raisons de non réponse du Greeter', max_length=500, null=True, verbose_name='Raisons de non réponse du Greeter'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='reason_no_reply_greeter_cluster_fr',
            field=models.CharField(default=' ', help_text='Saisir les raisons de non réponse du Greeter', max_length=500, null=True, verbose_name='Raisons de non réponse du Greeter'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='reason_no_reply_visitor_cluster',
            field=models.CharField(default=' ', help_text='Saisir les raisons de non réponse du visiteur', max_length=500, verbose_name='Raisons de non réponse du visiteur'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='reason_no_reply_visitor_cluster_de',
            field=models.CharField(default=' ', help_text='Saisir les raisons de non réponse du visiteur', max_length=500, null=True, verbose_name='Raisons de non réponse du visiteur'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='reason_no_reply_visitor_cluster_en_us',
            field=models.CharField(default=' ', help_text='Saisir les raisons de non réponse du visiteur', max_length=500, null=True, verbose_name='Raisons de non réponse du visiteur'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='reason_no_reply_visitor_cluster_es',
            field=models.CharField(default=' ', help_text='Saisir les raisons de non réponse du visiteur', max_length=500, null=True, verbose_name='Raisons de non réponse du visiteur'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='reason_no_reply_visitor_cluster_fr',
            field=models.CharField(default=' ', help_text='Saisir les raisons de non réponse du visiteur', max_length=500, null=True, verbose_name='Raisons de non réponse du visiteur'),
        ),
    ]
