# Generated by Django 5.2.3 on 2025-10-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0004_alter_cluster_list_experience_cluster_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='lang_com',
        ),
        migrations.AddField(
            model_name='cluster',
            name='langs_com',
            field=models.JSONField(blank=True, default=list, help_text='Liste des langues de communication', verbose_name='Langues de communication'),
        ),
    ]
