# Generated by Django 5.2.3 on 2025-10-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0005_remove_cluster_lang_com_cluster_langs_com'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='langs_com',
        ),
        migrations.AddField(
            model_name='cluster',
            name='lang_com',
            field=models.CharField(choices=[('en-us', 'English (US)'), ('fr', 'Français'), ('de', 'Deutsch'), ('es', 'Español')], default='fr', help_text='Langue de communication de base du cluster', max_length=5, verbose_name='Langue de communication'),
        ),
    ]
