# Generated by Django 5.2.3 on 2025-10-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0006_remove_cluster_langs_com_cluster_lang_com'),
        ('core', '0004_alter_email_mailjet_lang_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='lang_com',
        ),
        migrations.AddField(
            model_name='cluster',
            name='langs_com',
            field=models.ManyToManyField(blank=True, help_text='Sélectionner les langues de communication du cluster', to='core.language_communication', verbose_name='Langues de communication'),
        ),
    ]
