# Generated by Django 5.2.3 on 2025-10-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0007_remove_cluster_lang_com_cluster_langs_com'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='statut_cluster',
            field=models.CharField(choices=[('Drafts', 'Brouillon'), ('Active', 'Actif'), ('Inactive', 'Inactif'), ('Désactivated', 'Désactivé')], default='Drafts', help_text='Statut du cluster', max_length=15, verbose_name='Statut'),
        ),
    ]
