# Generated by Django 5.2.3 on 2025-10-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0008_cluster_statut_cluster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='statut_cluster',
            field=models.CharField(choices=[('Drafts', 'Brouillon'), ('Active', 'Actif'), ('Inactive', 'Inactif'), ('Désactivated', 'Désactivé')], default='Drafts', help_text='Saisir le statut du cluster', max_length=15, verbose_name='Statut'),
        ),
    ]
