# Generated by Django 5.2.3 on 2025-10-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0009_alter_cluster_statut_cluster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='list_experience_cluster',
            field=models.CharField(default=' ', help_text='Saisir les expériences des Greeter', max_length=500, verbose_name='Expériences des Greeters'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='list_experience_cluster_de',
            field=models.CharField(default=' ', help_text='Saisir les expériences des Greeter', max_length=500, null=True, verbose_name='Expériences des Greeters'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='list_experience_cluster_en_us',
            field=models.CharField(default=' ', help_text='Saisir les expériences des Greeter', max_length=500, null=True, verbose_name='Expériences des Greeters'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='list_experience_cluster_es',
            field=models.CharField(default=' ', help_text='Saisir les expériences des Greeter', max_length=500, null=True, verbose_name='Expériences des Greeters'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='list_experience_cluster_fr',
            field=models.CharField(default=' ', help_text='Saisir les expériences des Greeter', max_length=500, null=True, verbose_name='Expériences des Greeters'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='url_biblio_Greeter_cluster',
            field=models.URLField(blank=True, default=' ', help_text="Saisir l'URL de la bibliothèque pour les Greeter", verbose_name='URL de la bibliothèque Cluster des Greeter'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='url_biblio_cluster',
            field=models.URLField(blank=True, default=' ', help_text="Saisir l'URL de la bibliothèque pour les destinations", verbose_name='URL de la bibliothèque Cluster des destinations'),
        ),
    ]
