# Generated by Django 5.2.3 on 2025-10-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0010_alter_cluster_list_experience_cluster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='param_nbr_part_cluster',
            field=models.IntegerField(default=6, help_text='Nombre maximun de visiteurs pour le cluster', verbose_name='Nombre maximun de participants'),
        ),
    ]
