# Generated by Django 5.2.3 on 2025-10-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0011_alter_cluster_param_nbr_part_cluster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='code_cluster',
            field=models.CharField(default=' ', editable=False, max_length=5, unique=True, verbose_name='Code'),
        ),
    ]
