# Generated by Django 5.2.3 on 2025-10-29 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0012_alter_cluster_code_cluster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='admin_alt_cluster',
            field=models.ForeignKey(blank=True, help_text="Saisir l'administrateur alternatif parmi les utilisateurs ou en créer un", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_alt_cluster', to=settings.AUTH_USER_MODEL, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='admin_cluster',
            field=models.ForeignKey(blank=True, help_text="Saisir l'administrateur parmi les utilisateurs ou en créer un", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_cluster', to=settings.AUTH_USER_MODEL, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='code_cluster',
            field=models.CharField(default=' ', max_length=5, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='country_admin_alt_cluster',
            field=models.CharField(blank=True, default=' ', help_text="Saisir le pays de l'admnistrateur alternatif", max_length=30, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='country_admin_cluster',
            field=models.CharField(default=' ', help_text="Saisir le pays de l'administrateur", max_length=30, verbose_name='Pays'),
        ),
    ]
