# Generated by Django 5.2.3 on 2025-11-01 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0013_alter_cluster_admin_alt_cluster_and_more'),
        ('core', '0008_alter_fieldpermission_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='country_admin_alt_cluster',
            field=models.ForeignKey(blank=True, default=' ', help_text="Saisir le pays de l'admnistrateur alternatif", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_admin_alt_cluster', to='core.pays', verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='country_admin_cluster',
            field=models.ForeignKey(blank=True, default=' ', help_text="Saisir le pays de l'administrateur", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_admin_cluster', to='core.pays', verbose_name='Pays'),
        ),
    ]
