# Generated by Django 5.2.3 on 2025-11-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0014_alter_cluster_country_admin_alt_cluster_and_more'),
        ('core', '0009_beneficiaire_nom_beneficiaire_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='langs_com',
            field=models.ManyToManyField(help_text='Sélectionner les langues de communication du cluster', related_name='langs_com', to='core.language_communication', verbose_name='Langues de communication'),
        ),
    ]
