# Generated by Django 5.2.3 on 2025-12-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0015_alter_cluster_langs_com'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience_Greeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_greeter', models.CharField(default="Pas d'expérience", help_text="Saisir l'expérience du Greeter", max_length=100, verbose_name='Expérience')),
                ('experience_greeter_en_us', models.CharField(default="Pas d'expérience", help_text="Saisir l'expérience du Greeter", max_length=100, null=True, verbose_name='Expérience')),
                ('experience_greeter_fr', models.CharField(default="Pas d'expérience", help_text="Saisir l'expérience du Greeter", max_length=100, null=True, verbose_name='Expérience')),
                ('experience_greeter_de', models.CharField(default="Pas d'expérience", help_text="Saisir l'expérience du Greeter", max_length=100, null=True, verbose_name='Expérience')),
                ('experience_greeter_es', models.CharField(default="Pas d'expérience", help_text="Saisir l'expérience du Greeter", max_length=100, null=True, verbose_name='Expérience')),
            ],
        ),
        migrations.CreateModel(
            name='InterestCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_center', models.CharField(max_length=100, verbose_name="Centre d'intérêt")),
            ],
        ),
        migrations.AlterField(
            model_name='cluster',
            name='list_experience_cluster',
            field=models.CharField(default=' ', help_text='Saisir les expériences du Greeter', max_length=500, verbose_name='Liste des expériences'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='list_experience_cluster_de',
            field=models.CharField(default=' ', help_text='Saisir les expériences du Greeter', max_length=500, null=True, verbose_name='Liste des expériences'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='list_experience_cluster_en_us',
            field=models.CharField(default=' ', help_text='Saisir les expériences du Greeter', max_length=500, null=True, verbose_name='Liste des expériences'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='list_experience_cluster_es',
            field=models.CharField(default=' ', help_text='Saisir les expériences du Greeter', max_length=500, null=True, verbose_name='Liste des expériences'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='list_experience_cluster_fr',
            field=models.CharField(default=' ', help_text='Saisir les expériences du Greeter', max_length=500, null=True, verbose_name='Liste des expériences'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='profil_interet_cluster',
            field=models.CharField(default=' ', help_text="Saisir les profils d'intérêt du Greeter", max_length=500, verbose_name="Liste des profils d'intérêt"),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='profil_interet_cluster_de',
            field=models.CharField(default=' ', help_text="Saisir les profils d'intérêt du Greeter", max_length=500, null=True, verbose_name="Liste des profils d'intérêt"),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='profil_interet_cluster_en_us',
            field=models.CharField(default=' ', help_text="Saisir les profils d'intérêt du Greeter", max_length=500, null=True, verbose_name="Liste des profils d'intérêt"),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='profil_interet_cluster_es',
            field=models.CharField(default=' ', help_text="Saisir les profils d'intérêt du Greeter", max_length=500, null=True, verbose_name="Liste des profils d'intérêt"),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='profil_interet_cluster_fr',
            field=models.CharField(default=' ', help_text="Saisir les profils d'intérêt du Greeter", max_length=500, null=True, verbose_name="Liste des profils d'intérêt"),
        ),
    ]
