# Generated by Django 5.2.3 on 2025-12-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0016_experience_greeter_interestcenter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notoriety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notoriety', models.CharField(max_length=100, verbose_name='Notoriété')),
            ],
        ),
        migrations.CreateModel(
            name='Reason_No_Response_Greeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_no_response_greeter', models.CharField(max_length=100, verbose_name='Raison de non réponse du Greeter')),
            ],
        ),
        migrations.CreateModel(
            name='Reason_No_Response_Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_no_response_visitor', models.CharField(max_length=100, verbose_name='Raison de non réponse du visiteur')),
            ],
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='list_experience_cluster_de',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='list_experience_cluster_en_us',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='list_experience_cluster_es',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='list_experience_cluster_fr',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='list_notoriety_cluster_de',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='list_notoriety_cluster_en_us',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='list_notoriety_cluster_es',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='list_notoriety_cluster_fr',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='profil_interet_cluster_de',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='profil_interet_cluster_en_us',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='profil_interet_cluster_es',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='profil_interet_cluster_fr',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='reason_no_reply_greeter_cluster_de',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='reason_no_reply_greeter_cluster_en_us',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='reason_no_reply_greeter_cluster_es',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='reason_no_reply_greeter_cluster_fr',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='reason_no_reply_visitor_cluster_de',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='reason_no_reply_visitor_cluster_en_us',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='reason_no_reply_visitor_cluster_es',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='reason_no_reply_visitor_cluster_fr',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='list_experience_cluster',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='profil_interet_cluster',
        ),
        migrations.AddField(
            model_name='cluster',
            name='list_experience_cluster',
            field=models.ManyToManyField(related_name='list_experience_cluster', to='cluster.experience_greeter'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='profil_interet_cluster',
            field=models.ManyToManyField(related_name='profil_interet_cluster', to='cluster.interestcenter'),
        ),
    ]
