# Generated by Django 5.2.3 on 2025-12-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0017_notoriety_reason_no_response_greeter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='list_notoriety_cluster',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='reason_no_reply_greeter_cluster',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='reason_no_reply_visitor_cluster',
        ),
        migrations.AddField(
            model_name='cluster',
            name='list_notoriety_cluster',
            field=models.ManyToManyField(related_name='list_notoriety_cluster', to='cluster.notoriety'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='reason_no_reply_greeter_cluster',
            field=models.ManyToManyField(related_name='reason_no_reply_greeter_cluster', to='cluster.reason_no_response_greeter'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='reason_no_reply_visitor_cluster',
            field=models.ManyToManyField(related_name='reason_no_reply_visitor_cluster', to='cluster.reason_no_response_visitor'),
        ),
    ]
