# Generated by Django 5.2.3 on 2025-12-28 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0018_remove_cluster_list_notoriety_cluster_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reason_no_response_greeter',
            old_name='reason_no_response_greeter',
            new_name='reason_no_reply_greeter',
        ),
        migrations.RenameField(
            model_name='reason_no_response_visitor',
            old_name='reason_no_response_visitor',
            new_name='reason_no_reply_visitor',
        ),
    ]
