# Generated by Django 5.2.3 on 2025-12-29 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0019_rename_reason_no_response_greeter_reason_no_response_greeter_reason_no_reply_greeter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cluster',
            old_name='list_experience_cluster',
            new_name='experience_greeter',
        ),
        migrations.RenameField(
            model_name='cluster',
            old_name='profil_interet_cluster',
            new_name='interest_center',
        ),
        migrations.RenameField(
            model_name='cluster',
            old_name='list_notoriety_cluster',
            new_name='notoriety',
        ),
        migrations.RenameField(
            model_name='cluster',
            old_name='reason_no_reply_greeter_cluster',
            new_name='reason_no_reply_greeter',
        ),
        migrations.RenameField(
            model_name='cluster',
            old_name='reason_no_reply_visitor_cluster',
            new_name='reason_no_reply_visitor',
        ),
    ]
