# Generated by Django 5.2.3 on 2025-12-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0020_rename_list_experience_cluster_cluster_experience_greeter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notoriety',
            name='notoriety_de',
            field=models.CharField(max_length=100, null=True, verbose_name='Notoriété'),
        ),
        migrations.AddField(
            model_name='notoriety',
            name='notoriety_en_us',
            field=models.CharField(max_length=100, null=True, verbose_name='Notoriété'),
        ),
        migrations.AddField(
            model_name='notoriety',
            name='notoriety_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Notoriété'),
        ),
        migrations.AddField(
            model_name='notoriety',
            name='notoriety_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Notoriété'),
        ),
        migrations.AddField(
            model_name='reason_no_response_greeter',
            name='reason_no_reply_greeter_de',
            field=models.CharField(max_length=100, null=True, verbose_name='Raison de non réponse du Greeter'),
        ),
        migrations.AddField(
            model_name='reason_no_response_greeter',
            name='reason_no_reply_greeter_en_us',
            field=models.CharField(max_length=100, null=True, verbose_name='Raison de non réponse du Greeter'),
        ),
        migrations.AddField(
            model_name='reason_no_response_greeter',
            name='reason_no_reply_greeter_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Raison de non réponse du Greeter'),
        ),
        migrations.AddField(
            model_name='reason_no_response_greeter',
            name='reason_no_reply_greeter_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Raison de non réponse du Greeter'),
        ),
        migrations.AddField(
            model_name='reason_no_response_visitor',
            name='reason_no_reply_visitor_de',
            field=models.CharField(max_length=100, null=True, verbose_name='Raison de non réponse du visiteur'),
        ),
        migrations.AddField(
            model_name='reason_no_response_visitor',
            name='reason_no_reply_visitor_en_us',
            field=models.CharField(max_length=100, null=True, verbose_name='Raison de non réponse du visiteur'),
        ),
        migrations.AddField(
            model_name='reason_no_response_visitor',
            name='reason_no_reply_visitor_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Raison de non réponse du visiteur'),
        ),
        migrations.AddField(
            model_name='reason_no_response_visitor',
            name='reason_no_reply_visitor_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Raison de non réponse du visiteur'),
        ),
    ]
