# Generated by Django 5.2.3 on 2025-12-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0021_notoriety_notoriety_de_notoriety_notoriety_en_us_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestcenter',
            name='interest_center_de',
            field=models.CharField(max_length=100, null=True, verbose_name="Centre d'intérêt"),
        ),
        migrations.AddField(
            model_name='interestcenter',
            name='interest_center_en_us',
            field=models.CharField(max_length=100, null=True, verbose_name="Centre d'intérêt"),
        ),
        migrations.AddField(
            model_name='interestcenter',
            name='interest_center_es',
            field=models.CharField(max_length=100, null=True, verbose_name="Centre d'intérêt"),
        ),
        migrations.AddField(
            model_name='interestcenter',
            name='interest_center_fr',
            field=models.CharField(max_length=100, null=True, verbose_name="Centre d'intérêt"),
        ),
    ]
